// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         challengeSid: "ChallengeSid",
 *         ttl: 150
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         challengeSid: "ChallengeSid"
 *     }
 */
export interface CreateNotificationsRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity: string;
    /** The unique SID identifier of the Challenge. */
    challengeSid: string;
    /** How long, in seconds, the notification is valid. Can be an integer between 0 and 300. Default is 300. Delivery is attempted until the TTL elapses, even if the device is offline. 0 means that the notification delivery is attempted immediately, only once, and is not stored for future delivery. */
    ttl?: number;
}
