// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateMessagingConfigurationsRequest: core.serialization.Schema<
    serializers.CreateMessagingConfigurationsRequest.Raw,
    Omit<Twilio.CreateMessagingConfigurationsRequest, "serviceSid">
> = core.serialization.object({
    country: core.serialization.property("Country", core.serialization.string()),
    messagingServiceSid: core.serialization.property("MessagingServiceSid", core.serialization.string()),
});

export declare namespace CreateMessagingConfigurationsRequest {
    export interface Raw {
        Country: string;
        MessagingServiceSid: string;
    }
}
