// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateMessagingConfigurationsRequest: core.serialization.Schema<
    serializers.UpdateMessagingConfigurationsRequest.Raw,
    Omit<Twilio.UpdateMessagingConfigurationsRequest, "serviceSid" | "country">
> = core.serialization.object({
    messagingServiceSid: core.serialization.property("MessagingServiceSid", core.serialization.string()),
});

export declare namespace UpdateMessagingConfigurationsRequest {
    export interface Raw {
        MessagingServiceSid: string;
    }
}
