// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2ServiceRateLimitBucket } from "../../../types/VerifyV2ServiceRateLimitBucket.js";
import { ListBucketsResponseMeta } from "./ListBucketsResponseMeta.js";

export const ListBucketsResponse: core.serialization.ObjectSchema<
    serializers.ListBucketsResponse.Raw,
    Twilio.ListBucketsResponse
> = core.serialization.object({
    buckets: core.serialization.list(VerifyV2ServiceRateLimitBucket).optional(),
    meta: ListBucketsResponseMeta.optional(),
});

export declare namespace ListBucketsResponse {
    export interface Raw {
        buckets?: VerifyV2ServiceRateLimitBucket.Raw[] | null;
        meta?: ListBucketsResponseMeta.Raw | null;
    }
}
