// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2ServiceMessagingConfiguration } from "../../../types/VerifyV2ServiceMessagingConfiguration.js";
import { ListMessagingConfigurationsResponseMeta } from "./ListMessagingConfigurationsResponseMeta.js";

export const ListMessagingConfigurationsResponse: core.serialization.ObjectSchema<
    serializers.ListMessagingConfigurationsResponse.Raw,
    Twilio.ListMessagingConfigurationsResponse
> = core.serialization.object({
    messagingConfigurations: core.serialization.property(
        "messaging_configurations",
        core.serialization.list(VerifyV2ServiceMessagingConfiguration).optional(),
    ),
    meta: ListMessagingConfigurationsResponseMeta.optional(),
});

export declare namespace ListMessagingConfigurationsResponse {
    export interface Raw {
        messaging_configurations?: VerifyV2ServiceMessagingConfiguration.Raw[] | null;
        meta?: ListMessagingConfigurationsResponseMeta.Raw | null;
    }
}
