// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePasskeyFactorsRequestConfigUserVerification: core.serialization.Schema<
    serializers.CreatePasskeyFactorsRequestConfigUserVerification.Raw,
    Twilio.CreatePasskeyFactorsRequestConfigUserVerification
> = core.serialization.enum_(["required", "preferred", "discouraged"]);

export declare namespace CreatePasskeyFactorsRequestConfigUserVerification {
    export type Raw = "required" | "preferred" | "discouraged";
}
