// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePasskeyFactorsRequestConfigAuthenticatorAttachment: core.serialization.Schema<
    serializers.CreatePasskeyFactorsRequestConfigAuthenticatorAttachment.Raw,
    Twilio.CreatePasskeyFactorsRequestConfigAuthenticatorAttachment
> = core.serialization.enum_(["platform", "cross-platform", "any"]);

export declare namespace CreatePasskeyFactorsRequestConfigAuthenticatorAttachment {
    export type Raw = "platform" | "cross-platform" | "any";
}
