// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePasskeyFactorsResponseFactorType: core.serialization.Schema<
    serializers.CreatePasskeyFactorsResponseFactorType.Raw,
    Twilio.CreatePasskeyFactorsResponseFactorType
> = core.serialization.enum_(["push", "totp", "passkeys"]);

export declare namespace CreatePasskeyFactorsResponseFactorType {
    export type Raw = "push" | "totp" | "passkeys";
}
