// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePasskeyFactorsRequestConfigRelyingParty: core.serialization.ObjectSchema<
    serializers.CreatePasskeyFactorsRequestConfigRelyingParty.Raw,
    Twilio.CreatePasskeyFactorsRequestConfigRelyingParty
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    origins: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace CreatePasskeyFactorsRequestConfigRelyingParty {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        origins?: string[] | null;
    }
}
