// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePasskeyFactorsRequestConfigDiscoverableCredentials: core.serialization.Schema<
    serializers.CreatePasskeyFactorsRequestConfigDiscoverableCredentials.Raw,
    Twilio.CreatePasskeyFactorsRequestConfigDiscoverableCredentials
> = core.serialization.enum_(["required", "preferred", "discouraged"]);

export declare namespace CreatePasskeyFactorsRequestConfigDiscoverableCredentials {
    export type Raw = "required" | "preferred" | "discouraged";
}
