// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreatePasskeyFactorsRequestConfigAuthenticatorAttachment } from "./CreatePasskeyFactorsRequestConfigAuthenticatorAttachment.js";
import { CreatePasskeyFactorsRequestConfigDiscoverableCredentials } from "./CreatePasskeyFactorsRequestConfigDiscoverableCredentials.js";
import { CreatePasskeyFactorsRequestConfigRelyingParty } from "./CreatePasskeyFactorsRequestConfigRelyingParty.js";
import { CreatePasskeyFactorsRequestConfigUserVerification } from "./CreatePasskeyFactorsRequestConfigUserVerification.js";

export const CreatePasskeyFactorsRequestConfig: core.serialization.ObjectSchema<
    serializers.CreatePasskeyFactorsRequestConfig.Raw,
    Twilio.CreatePasskeyFactorsRequestConfig
> = core.serialization.object({
    relyingParty: core.serialization.property(
        "relying_party",
        CreatePasskeyFactorsRequestConfigRelyingParty.optional(),
    ),
    authenticatorAttachment: core.serialization.property(
        "authenticator_attachment",
        CreatePasskeyFactorsRequestConfigAuthenticatorAttachment.optional(),
    ),
    discoverableCredentials: core.serialization.property(
        "discoverable_credentials",
        CreatePasskeyFactorsRequestConfigDiscoverableCredentials.optional(),
    ),
    userVerification: core.serialization.property(
        "user_verification",
        CreatePasskeyFactorsRequestConfigUserVerification.optional(),
    ),
});

export declare namespace CreatePasskeyFactorsRequestConfig {
    export interface Raw {
        relying_party?: CreatePasskeyFactorsRequestConfigRelyingParty.Raw | null;
        authenticator_attachment?: CreatePasskeyFactorsRequestConfigAuthenticatorAttachment.Raw | null;
        discoverable_credentials?: CreatePasskeyFactorsRequestConfigDiscoverableCredentials.Raw | null;
        user_verification?: CreatePasskeyFactorsRequestConfigUserVerification.Raw | null;
    }
}
