// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2ServiceEntityFactor } from "../../../types/VerifyV2ServiceEntityFactor.js";
import { ListFactorsResponseMeta } from "./ListFactorsResponseMeta.js";

export const ListFactorsResponse: core.serialization.ObjectSchema<
    serializers.ListFactorsResponse.Raw,
    Twilio.ListFactorsResponse
> = core.serialization.object({
    factors: core.serialization.list(VerifyV2ServiceEntityFactor).optional(),
    meta: ListFactorsResponseMeta.optional(),
});

export declare namespace ListFactorsResponse {
    export interface Raw {
        factors?: VerifyV2ServiceEntityFactor.Raw[] | null;
        meta?: ListFactorsResponseMeta.Raw | null;
    }
}
