// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyPasskeyFactorsResponseFactorType } from "./VerifyPasskeyFactorsResponseFactorType.js";
import { VerifyPasskeyFactorsResponseStatus } from "./VerifyPasskeyFactorsResponseStatus.js";

export const VerifyPasskeyFactorsResponse: core.serialization.ObjectSchema<
    serializers.VerifyPasskeyFactorsResponse.Raw,
    Twilio.VerifyPasskeyFactorsResponse
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    entitySid: core.serialization.property("entity_sid", core.serialization.string().optionalNullable()),
    identity: core.serialization.string().optionalNullable(),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    friendlyName: core.serialization.property("friendly_name", core.serialization.string().optionalNullable()),
    status: VerifyPasskeyFactorsResponseStatus.optional(),
    factorType: core.serialization.property("factor_type", VerifyPasskeyFactorsResponseFactorType.optional()),
    config: core.serialization.unknown().optionalNullable(),
    metadata: core.serialization.unknown().optionalNullable(),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyPasskeyFactorsResponse {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        entity_sid?: (string | null | undefined) | null;
        identity?: (string | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        friendly_name?: (string | null | undefined) | null;
        status?: VerifyPasskeyFactorsResponseStatus.Raw | null;
        factor_type?: VerifyPasskeyFactorsResponseFactorType.Raw | null;
        config?: (unknown | null | undefined) | null;
        metadata?: (unknown | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
