// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const VerifyPasskeyFactorsRequestAuthenticatorAttachment: core.serialization.Schema<
    serializers.VerifyPasskeyFactorsRequestAuthenticatorAttachment.Raw,
    Twilio.VerifyPasskeyFactorsRequestAuthenticatorAttachment
> = core.serialization.enum_(["platform", "cross-platform"]);

export declare namespace VerifyPasskeyFactorsRequestAuthenticatorAttachment {
    export type Raw = "platform" | "cross-platform";
}
