// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const VerifyPasskeyFactorsRequestResponseTransportsItem: core.serialization.Schema<
    serializers.VerifyPasskeyFactorsRequestResponseTransportsItem.Raw,
    Twilio.VerifyPasskeyFactorsRequestResponseTransportsItem
> = core.serialization.enum_(["usb", "nfc", "ble", "smart-card", "internal", "hybrid"]);

export declare namespace VerifyPasskeyFactorsRequestResponseTransportsItem {
    export type Raw = "usb" | "nfc" | "ble" | "smart-card" | "internal" | "hybrid";
}
