// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const VerifyPasskeyFactorsResponseFactorType: core.serialization.Schema<
    serializers.VerifyPasskeyFactorsResponseFactorType.Raw,
    Twilio.VerifyPasskeyFactorsResponseFactorType
> = core.serialization.enum_(["push", "totp", "passkeys"]);

export declare namespace VerifyPasskeyFactorsResponseFactorType {
    export type Raw = "push" | "totp" | "passkeys";
}
