// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyPasskeyFactorsRequestResponseTransportsItem } from "./VerifyPasskeyFactorsRequestResponseTransportsItem.js";

export const VerifyPasskeyFactorsRequestResponse: core.serialization.ObjectSchema<
    serializers.VerifyPasskeyFactorsRequestResponse.Raw,
    Twilio.VerifyPasskeyFactorsRequestResponse
> = core.serialization.object({
    attestationObject: core.serialization.string().optional(),
    clientDataJson: core.serialization.property("clientDataJSON", core.serialization.string().optional()),
    transports: core.serialization.list(VerifyPasskeyFactorsRequestResponseTransportsItem).optional(),
});

export declare namespace VerifyPasskeyFactorsRequestResponse {
    export interface Raw {
        attestationObject?: string | null;
        clientDataJSON?: string | null;
        transports?: VerifyPasskeyFactorsRequestResponseTransportsItem.Raw[] | null;
    }
}
