// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListRateLimitsResponse {
    rateLimits?: Twilio.VerifyV2ServiceRateLimit[];
    meta?: Twilio.ListRateLimitsResponseMeta;
}
