// This file was auto-generated by Fern from our API Definition.

/** The Type of the Factor. Currently only `push` is supported. */
export const AccessTokenEnumFactorTypes = {
    Push: "push",
} as const;
export type AccessTokenEnumFactorTypes = (typeof AccessTokenEnumFactorTypes)[keyof typeof AccessTokenEnumFactorTypes];
