// This file was auto-generated by Fern from our API Definition.

/** The Status of this Challenge. One of `pending`, `expired`, `approved` or `denied`. */
export const ChallengeEnumChallengeStatuses = {
    Pending: "pending",
    Expired: "expired",
    Approved: "approved",
    Denied: "denied",
} as const;
export type ChallengeEnumChallengeStatuses =
    (typeof ChallengeEnumChallengeStatuses)[keyof typeof ChallengeEnumChallengeStatuses];
