// This file was auto-generated by Fern from our API Definition.

/** The Factor Type of this Challenge. Currently `push` and `totp` are supported. */
export const ChallengeEnumFactorTypes = {
    Push: "push",
    Totp: "totp",
    Passkeys: "passkeys",
} as const;
export type ChallengeEnumFactorTypes = (typeof ChallengeEnumFactorTypes)[keyof typeof ChallengeEnumFactorTypes];
