// This file was auto-generated by Fern from our API Definition.

export const ChallengeEnumListOrders = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ChallengeEnumListOrders = (typeof ChallengeEnumListOrders)[keyof typeof ChallengeEnumListOrders];
