// This file was auto-generated by Fern from our API Definition.

/** Reason for the Challenge to be in certain `status`. One of `none`, `not_needed` or `not_requested`. */
export const ChallengeEnumChallengeReasons = {
    None: "none",
    NotNeeded: "not_needed",
    NotRequested: "not_requested",
} as const;
export type ChallengeEnumChallengeReasons =
    (typeof ChallengeEnumChallengeReasons)[keyof typeof ChallengeEnumChallengeReasons];
