// This file was auto-generated by Fern from our API Definition.

export const FactorEnumTotpAlgorithms = {
    Sha1: "sha1",
    Sha256: "sha256",
    Sha512: "sha512",
} as const;
export type FactorEnumTotpAlgorithms = (typeof FactorEnumTotpAlgorithms)[keyof typeof FactorEnumTotpAlgorithms];
