// This file was auto-generated by Fern from our API Definition.

export const FactorEnumNotificationPlatforms = {
    Apn: "apn",
    Fcm: "fcm",
    None: "none",
} as const;
export type FactorEnumNotificationPlatforms =
    (typeof FactorEnumNotificationPlatforms)[keyof typeof FactorEnumNotificationPlatforms];
