// This file was auto-generated by Fern from our API Definition.

/** The Status of this Factor. One of `unverified` or `verified`. */
export const FactorEnumFactorStatuses = {
    Unverified: "unverified",
    Verified: "verified",
} as const;
export type FactorEnumFactorStatuses = (typeof FactorEnumFactorStatuses)[keyof typeof FactorEnumFactorStatuses];
