// This file was auto-generated by Fern from our API Definition.

/** The Type of this Factor. Currently `push` and `totp` are supported. */
export const FactorEnumFactorTypes = {
    Push: "push",
    Totp: "totp",
    Passkeys: "passkeys",
} as const;
export type FactorEnumFactorTypes = (typeof FactorEnumFactorTypes)[keyof typeof FactorEnumFactorTypes];
