// This file was auto-generated by Fern from our API Definition.

/** The Type of this Form. Currently only `form-push` is supported. */
export const FormEnumFormTypes = {
    FormPush: "form-push",
} as const;
export type FormEnumFormTypes = (typeof FormEnumFormTypes)[keyof typeof FormEnumFormTypes];
