// This file was auto-generated by Fern from our API Definition.

/** The Type of this Factor. Currently `push` and `totp` are supported. */
export const NewFactorEnumFactorTypes = {
    Push: "push",
    Totp: "totp",
    Passkeys: "passkeys",
} as const;
export type NewFactorEnumFactorTypes = (typeof NewFactorEnumFactorTypes)[keyof typeof NewFactorEnumFactorTypes];
