// This file was auto-generated by Fern from our API Definition.

export const NewFactorEnumNotificationPlatforms = {
    Apn: "apn",
    Fcm: "fcm",
    None: "none",
} as const;
export type NewFactorEnumNotificationPlatforms =
    (typeof NewFactorEnumNotificationPlatforms)[keyof typeof NewFactorEnumNotificationPlatforms];
