// This file was auto-generated by Fern from our API Definition.

export const NewFactorEnumTotpAlgorithms = {
    Sha1: "sha1",
    Sha256: "sha256",
    Sha512: "sha512",
} as const;
export type NewFactorEnumTotpAlgorithms =
    (typeof NewFactorEnumTotpAlgorithms)[keyof typeof NewFactorEnumTotpAlgorithms];
