// This file was auto-generated by Fern from our API Definition.

export interface TooManyRequestsErrorBody {
    /** Twilio-specific error code */
    code?: number;
    /** Error message */
    message?: string;
    /** Link to Error Code References */
    moreInfo?: string;
    /** HTTP response status code */
    status?: number;
}
