// This file was auto-generated by Fern from our API Definition.

export interface VerifyV2ServiceEntity {
    /** A 34 character string that uniquely identifies this Entity. */
    sid?: string | null;
    /** The unique external identifier for the Entity of the Service. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity?: string | null;
    /** The unique SID identifier of the Account. */
    accountSid?: string | null;
    /** The unique SID identifier of the Service. */
    serviceSid?: string | null;
    /** The date that this Entity was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateCreated?: Date | null;
    /** The date that this Entity was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateUpdated?: Date | null;
    /** The URL of this resource. */
    url?: string | null;
    /** Contains a dictionary of URL links to nested resources of this Entity. */
    links?: Record<string, unknown> | null;
}
