// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../index.js";

export interface VerifyV2ServiceAccessToken {
    /** A 34 character string that uniquely identifies this Access Token. */
    sid?: string | null;
    /** The unique SID identifier of the Account. */
    accountSid?: string | null;
    /** The unique SID identifier of the Verify Service. */
    serviceSid?: string | null;
    /** The unique external identifier for the Entity of the Service. */
    entityIdentity?: string | null;
    factorType?: Twilio.AccessTokenEnumFactorTypes;
    /** A human readable description of this factor, up to 64 characters. For a push factor, this can be the device's name. */
    factorFriendlyName?: string | null;
    /** The access token generated for enrollment, this is an encrypted json web token. */
    token?: string | null;
    /** The URL of this resource. */
    url?: string | null;
    /** How long, in seconds, the access token is valid. Max: 5 minutes */
    ttl?: number;
    /** The date that this access token was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateCreated?: Date | null;
}
