// This file was auto-generated by Fern from our API Definition.

/** Risk_check overrides Fraud Prevention measures like Fraud Guard, Geo Permissions etc per verification attempt basis, allowing Verify to block traffic considered fraudulent if enabled or bypass active protections if disabled. Can be: `enable`(default) or `disable`. For SMS channel only. */
export const VerificationEnumRiskCheck = {
    Enable: "enable",
    Disable: "disable",
} as const;
export type VerificationEnumRiskCheck = (typeof VerificationEnumRiskCheck)[keyof typeof VerificationEnumRiskCheck];
