// This file was auto-generated by Fern from our API Definition.

/** The status of the verification. Can be: `pending`, `approved`, `canceled`, `max_attempts_reached`, `deleted`, `failed` or `expired`. */
export const VerificationEnumStatus = {
    Canceled: "canceled",
    Approved: "approved",
} as const;
export type VerificationEnumStatus = (typeof VerificationEnumStatus)[keyof typeof VerificationEnumStatus];
