// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../index.js";

export interface VerifyV2ServiceWebhook {
    /** The unique string that we created to identify the Webhook resource. */
    sid?: string | null;
    /** The unique SID identifier of the Service. */
    serviceSid?: string | null;
    /** The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service resource. */
    accountSid?: string | null;
    /** The string that you assigned to describe the webhook. **This value should not contain PII.** */
    friendlyName?: string | null;
    /** The array of events that this Webhook is subscribed to. Possible event types: `*, factor.deleted, factor.created, factor.verified, challenge.approved, challenge.denied` */
    eventTypes?: string[] | null;
    status?: Twilio.WebhookEnumStatus;
    version?: Twilio.WebhookEnumVersion;
    /** The URL associated with this Webhook. */
    webhookUrl?: string | null;
    webhookMethod?: Twilio.WebhookEnumMethods;
    /** The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateCreated?: Date | null;
    /** The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateUpdated?: Date | null;
    /** The absolute URL of the Webhook resource. */
    url?: string | null;
}
