// This file was auto-generated by Fern from our API Definition.

export interface VerifyV2ServiceRateLimitBucket {
    /** A 34 character string that uniquely identifies this Bucket. */
    sid?: string | null;
    /** The Twilio-provided string that uniquely identifies the Rate Limit resource. */
    rateLimitSid?: string | null;
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with. */
    serviceSid?: string | null;
    /** The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Rate Limit resource. */
    accountSid?: string | null;
    /** Maximum number of requests permitted in during the interval. */
    max?: number;
    /** Number of seconds that the rate limit will be enforced over. */
    interval?: number;
    /** The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format. */
    dateCreated?: Date | null;
    /** The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format. */
    dateUpdated?: Date | null;
    /** The URL of this resource. */
    url?: string | null;
}
