// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../index.js";

export interface VerifyV2VerificationAttempt {
    /** The SID that uniquely identifies the verification attempt resource. */
    sid?: string | null;
    /** The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Verification resource. */
    accountSid?: string | null;
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) used to generate the attempt. */
    serviceSid?: string | null;
    /** The SID of the [Verification](https://www.twilio.com/docs/verify/api/verification) that generated the attempt. */
    verificationSid?: string | null;
    /** The date that this Attempt was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateCreated?: Date | null;
    /** The date that this Attempt was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateUpdated?: Date | null;
    conversionStatus?: Twilio.VerificationAttemptEnumConversionStatus;
    channel?: Twilio.VerificationAttemptEnumChannels;
    /** An object containing the charge for this verification attempt related to the channel costs and the currency used. The costs related to the succeeded verifications are not included. May not be immediately available. More information on pricing is available [here](https://www.twilio.com/en-us/verify/pricing). */
    price?: unknown | null;
    /** An object containing the channel specific information for an attempt. */
    channelData?: unknown | null;
    url?: string | null;
}
