// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../index.js";

export interface VerifyV2ServiceEntityFactor {
    /** A 34 character string that uniquely identifies this Factor. */
    sid?: string | null;
    /** The unique SID identifier of the Account. */
    accountSid?: string | null;
    /** The unique SID identifier of the Service. */
    serviceSid?: string | null;
    /** The unique SID identifier of the Entity. */
    entitySid?: string | null;
    /** Customer unique identity for the Entity owner of the Factor. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity?: string | null;
    /** The date that this Factor was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateCreated?: Date | null;
    /** The date that this Factor was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateUpdated?: Date | null;
    /** A human readable description of this resource, up to 64 characters. For a push factor, this can be the device's name. */
    friendlyName?: string | null;
    status?: Twilio.FactorEnumFactorStatuses;
    factorType?: Twilio.FactorEnumFactorTypes;
    /** An object that contains configurations specific to a `factor_type`. */
    config?: unknown | null;
    /** Custom metadata associated with the factor. This is added by the Device/SDK directly to allow for the inclusion of device information. It must be a stringified JSON with only strings values eg. `{"os": "Android"}`. Can be up to 1024 characters in length. */
    metadata?: unknown | null;
    /** The URL of this resource. */
    url?: string | null;
}
