// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../index.js";

export interface VerifyV2Form {
    formType?: Twilio.FormEnumFormTypes;
    /** Object that contains the available forms for this type. This available forms are given in the standard [JSON Schema](https://json-schema.org/) format */
    forms?: unknown | null;
    /** Additional information for the available forms for this type. E.g. The separator string used for `binding` in a Factor push. */
    formMeta?: unknown | null;
    /** The URL to access the forms for this type. */
    url?: string | null;
}
