// This file was auto-generated by Fern from our API Definition.

/** A string specifying the conversion status of the verification. A conversion happens when the user is able to provide the correct code. Possible values are `CONVERTED` and `UNCONVERTED`. */
export const VerificationAttemptEnumConversionStatus = {
    Converted: "converted",
    Unconverted: "unconverted",
} as const;
export type VerificationAttemptEnumConversionStatus =
    (typeof VerificationAttemptEnumConversionStatus)[keyof typeof VerificationAttemptEnumConversionStatus];
