// This file was auto-generated by Fern from our API Definition.

export interface VerifyV2Safelist {
    /** The unique string that we created to identify the SafeList resource. */
    sid?: string | null;
    /** The phone number in SafeList. */
    phoneNumber?: string | null;
    /** The absolute URL of the SafeList resource. */
    url?: string | null;
}
