// This file was auto-generated by Fern from our API Definition.

export const VerificationAttemptEnumMessageStatus = {
    Queued: "queued",
    Sending: "sending",
    Sent: "sent",
    Failed: "failed",
    Delivered: "delivered",
    Undelivered: "undelivered",
    Receiving: "receiving",
    Received: "received",
    Accepted: "accepted",
    Scheduled: "scheduled",
    Read: "read",
    PartiallyDelivered: "partially_delivered",
    Canceled: "canceled",
} as const;
export type VerificationAttemptEnumMessageStatus =
    (typeof VerificationAttemptEnumMessageStatus)[keyof typeof VerificationAttemptEnumMessageStatus];
