// This file was auto-generated by Fern from our API Definition.

export const VerificationAttemptEnumAttemptStatus = {
    Confirmed: "confirmed",
    Unconfirmed: "unconfirmed",
    Expired: "expired",
} as const;
export type VerificationAttemptEnumAttemptStatus =
    (typeof VerificationAttemptEnumAttemptStatus)[keyof typeof VerificationAttemptEnumAttemptStatus];
