// This file was auto-generated by Fern from our API Definition.

export const VerificationAttemptsSummaryEnumChannels = {
    Sms: "sms",
    Call: "call",
    Email: "email",
    Whatsapp: "whatsapp",
    Rbm: "rbm",
} as const;
export type VerificationAttemptsSummaryEnumChannels =
    (typeof VerificationAttemptsSummaryEnumChannels)[keyof typeof VerificationAttemptsSummaryEnumChannels];
