// This file was auto-generated by Fern from our API Definition.

export interface VerifyV2VerificationTemplate {
    /** A 34 character string that uniquely identifies a Verification Template. */
    sid?: string | null;
    /** The unique SID identifier of the Account. */
    accountSid?: string | null;
    /** A descriptive string that you create to describe a Template. It can be up to 32 characters long. */
    friendlyName?: string | null;
    /** A list of channels that support the Template. Can include: sms, voice. */
    channels?: string[] | null;
    /** An object that contains the different translations of the template. Every translation is identified by the language short name and contains its respective information as the approval status, text and created/modified date. */
    translations?: unknown | null;
}
