// This file was auto-generated by Fern from our API Definition.

export const VerificationAttemptEnumCallStatus = {
    Queued: "queued",
    InProgress: "in-progress",
    Completed: "completed",
    Busy: "busy",
    Failed: "failed",
    NoAnswer: "no-answer",
    Ringing: "ringing",
    Canceled: "canceled",
} as const;
export type VerificationAttemptEnumCallStatus =
    (typeof VerificationAttemptEnumCallStatus)[keyof typeof VerificationAttemptEnumCallStatus];
