// This file was auto-generated by Fern from our API Definition.

/** A string specifying the communication channel used for the verification attempt. */
export const VerificationAttemptEnumChannels = {
    Sms: "sms",
    Call: "call",
    Email: "email",
    Whatsapp: "whatsapp",
    Rbm: "rbm",
} as const;
export type VerificationAttemptEnumChannels =
    (typeof VerificationAttemptEnumChannels)[keyof typeof VerificationAttemptEnumChannels];
