// This file was auto-generated by Fern from our API Definition.

/** The method to be used when calling the webhook's URL. */
export const WebhookEnumMethods = {
    Get: "GET",
    Post: "POST",
} as const;
export type WebhookEnumMethods = (typeof WebhookEnumMethods)[keyof typeof WebhookEnumMethods];
