// This file was auto-generated by Fern from our API Definition.

/** The webhook status. Default value is `enabled`. One of: `enabled` or `disabled` */
export const WebhookEnumStatus = {
    Enabled: "enabled",
    Disabled: "disabled",
} as const;
export type WebhookEnumStatus = (typeof WebhookEnumStatus)[keyof typeof WebhookEnumStatus];
