// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListWebhooksResponse {
    webhooks?: Twilio.VerifyV2ServiceWebhook[];
    meta?: Twilio.ListWebhooksResponseMeta;
}
