// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateRateLimitsRequest: core.serialization.Schema<
    serializers.CreateRateLimitsRequest.Raw,
    Omit<Twilio.CreateRateLimitsRequest, "serviceSid">
> = core.serialization.object({
    uniqueName: core.serialization.property("UniqueName", core.serialization.string()),
    description: core.serialization.property("Description", core.serialization.string().optional()),
});

export declare namespace CreateRateLimitsRequest {
    export interface Raw {
        UniqueName: string;
        Description?: string | null;
    }
}
