// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateRateLimitsRequest: core.serialization.Schema<
    serializers.UpdateRateLimitsRequest.Raw,
    Omit<Twilio.UpdateRateLimitsRequest, "serviceSid" | "sid">
> = core.serialization.object({
    description: core.serialization.property("Description", core.serialization.string().optional()),
});

export declare namespace UpdateRateLimitsRequest {
    export interface Raw {
        Description?: string | null;
    }
}
