// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumber: "+18001234567"
 *     }
 */
export interface CreateSafelistRequest {
    /** The phone number to be added in SafeList. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164). */
    phoneNumber: string;
}
