// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumber: "PhoneNumber"
 *     }
 */
export interface DeleteSafelistRequest {
    /** The phone number to be removed from SafeList. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164). */
    phoneNumber: string;
}
