// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateServicesRequest: core.serialization.Schema<
    serializers.CreateServicesRequest.Raw,
    Twilio.CreateServicesRequest
> = core.serialization.object({
    friendlyName: core.serialization.property("FriendlyName", core.serialization.string()),
    codeLength: core.serialization.property("CodeLength", core.serialization.number().optional()),
    lookupEnabled: core.serialization.property("LookupEnabled", core.serialization.boolean().optional()),
    skipSmsToLandlines: core.serialization.property("SkipSmsToLandlines", core.serialization.boolean().optional()),
    dtmfInputRequired: core.serialization.property("DtmfInputRequired", core.serialization.boolean().optional()),
    ttsName: core.serialization.property("TtsName", core.serialization.string().optional()),
    psd2Enabled: core.serialization.property("Psd2Enabled", core.serialization.boolean().optional()),
    doNotShareWarningEnabled: core.serialization.property(
        "DoNotShareWarningEnabled",
        core.serialization.boolean().optional(),
    ),
    customCodeEnabled: core.serialization.property("CustomCodeEnabled", core.serialization.boolean().optional()),
    pushIncludeDate: core.serialization.property("Push.IncludeDate", core.serialization.boolean().optional()),
    pushApnCredentialSid: core.serialization.property("Push.ApnCredentialSid", core.serialization.string().optional()),
    pushFcmCredentialSid: core.serialization.property("Push.FcmCredentialSid", core.serialization.string().optional()),
    totpIssuer: core.serialization.property("Totp.Issuer", core.serialization.string().optional()),
    totpTimeStep: core.serialization.property("Totp.TimeStep", core.serialization.number().optional()),
    totpCodeLength: core.serialization.property("Totp.CodeLength", core.serialization.number().optional()),
    totpSkew: core.serialization.property("Totp.Skew", core.serialization.number().optional()),
    defaultTemplateSid: core.serialization.property("DefaultTemplateSid", core.serialization.string().optional()),
    whatsappMsgServiceSid: core.serialization.property(
        "Whatsapp.MsgServiceSid",
        core.serialization.string().optional(),
    ),
    whatsappFrom: core.serialization.property("Whatsapp.From", core.serialization.string().optional()),
    passkeysRelyingPartyId: core.serialization.property(
        "Passkeys.RelyingParty.Id",
        core.serialization.string().optional(),
    ),
    passkeysRelyingPartyName: core.serialization.property(
        "Passkeys.RelyingParty.Name",
        core.serialization.string().optional(),
    ),
    passkeysRelyingPartyOrigins: core.serialization.property(
        "Passkeys.RelyingParty.Origins",
        core.serialization.string().optional(),
    ),
    passkeysAuthenticatorAttachment: core.serialization.property(
        "Passkeys.AuthenticatorAttachment",
        core.serialization.string().optional(),
    ),
    passkeysDiscoverableCredentials: core.serialization.property(
        "Passkeys.DiscoverableCredentials",
        core.serialization.string().optional(),
    ),
    passkeysUserVerification: core.serialization.property(
        "Passkeys.UserVerification",
        core.serialization.string().optional(),
    ),
    verifyEventSubscriptionEnabled: core.serialization.property(
        "VerifyEventSubscriptionEnabled",
        core.serialization.boolean().optional(),
    ),
});

export declare namespace CreateServicesRequest {
    export interface Raw {
        FriendlyName: string;
        CodeLength?: number | null;
        LookupEnabled?: boolean | null;
        SkipSmsToLandlines?: boolean | null;
        DtmfInputRequired?: boolean | null;
        TtsName?: string | null;
        Psd2Enabled?: boolean | null;
        DoNotShareWarningEnabled?: boolean | null;
        CustomCodeEnabled?: boolean | null;
        "Push.IncludeDate"?: boolean | null;
        "Push.ApnCredentialSid"?: string | null;
        "Push.FcmCredentialSid"?: string | null;
        "Totp.Issuer"?: string | null;
        "Totp.TimeStep"?: number | null;
        "Totp.CodeLength"?: number | null;
        "Totp.Skew"?: number | null;
        DefaultTemplateSid?: string | null;
        "Whatsapp.MsgServiceSid"?: string | null;
        "Whatsapp.From"?: string | null;
        "Passkeys.RelyingParty.Id"?: string | null;
        "Passkeys.RelyingParty.Name"?: string | null;
        "Passkeys.RelyingParty.Origins"?: string | null;
        "Passkeys.AuthenticatorAttachment"?: string | null;
        "Passkeys.DiscoverableCredentials"?: string | null;
        "Passkeys.UserVerification"?: string | null;
        VerifyEventSubscriptionEnabled?: boolean | null;
    }
}
