// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2VerificationTemplate } from "../../../types/VerifyV2VerificationTemplate.js";
import { ListTemplatesResponseMeta } from "./ListTemplatesResponseMeta.js";

export const ListTemplatesResponse: core.serialization.ObjectSchema<
    serializers.ListTemplatesResponse.Raw,
    Twilio.ListTemplatesResponse
> = core.serialization.object({
    templates: core.serialization.list(VerifyV2VerificationTemplate).optional(),
    meta: ListTemplatesResponseMeta.optional(),
});

export declare namespace ListTemplatesResponse {
    export interface Raw {
        templates?: VerifyV2VerificationTemplate.Raw[] | null;
        meta?: ListTemplatesResponseMeta.Raw | null;
    }
}
