// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListEntitiesResponse {
    entities?: Twilio.VerifyV2ServiceEntity[];
    meta?: Twilio.ListEntitiesResponseMeta;
}
