// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         friendlyName: "FriendlyName",
 *         identity: "ff483d1ff591898a9942916050d2ca3f",
 *         config: {
 *             relyingParty: {
 *                 id: "example.com",
 *                 name: "Example",
 *                 origins: ["https://example.com"]
 *             },
 *             authenticatorAttachment: "platform",
 *             discoverableCredentials: "preferred",
 *             userVerification: "preferred"
 *         }
 *     }
 */
export interface CreatePasskeyFactorsRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    friendlyName: string;
    identity: string;
    config?: Twilio.CreatePasskeyFactorsRequestConfig;
}
