// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         sid: "Sid",
 *         authPayload: "123456",
 *         friendlyName: "FriendlyName",
 *         configNotificationToken: "test_token",
 *         configSdkVersion: "1.0"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         sid: "Sid",
 *         authPayload: "123456",
 *         friendlyName: "My Friendly Name"
 *     }
 */
export interface UpdateFactorsRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** Customer unique identity for the Entity owner of the Factor. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity: string;
    /** A 34 character string that uniquely identifies this Factor. */
    sid: string;
    /** The optional payload needed to verify the Factor for the first time. E.g. for a TOTP, the numeric code. */
    authPayload?: string;
    /** The new friendly name of this Factor. It can be up to 64 characters. */
    friendlyName?: string;
    /** For APN, the device token. For FCM, the registration token. It is used to send the push notifications. Required when `factor_type` is `push`. If specified, this value must be between 32 and 255 characters long. */
    configNotificationToken?: string;
    /** The Verify Push SDK version used to configure the factor */
    configSdkVersion?: string;
    /** Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated every time_step seconds. Must be between 20 and 60 seconds, inclusive */
    configTimeStep?: number;
    /** The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be between 0 and 2, inclusive */
    configSkew?: number;
    /** Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive */
    configCodeLength?: number;
    configAlg?: Twilio.FactorEnumTotpAlgorithms;
    /**
     * The transport technology used to generate the Notification Token. Can be `apn`, `fcm` or `none`.
     *
     * Required when `factor_type` is `push`.
     */
    configNotificationPlatform?: string;
}
