// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         id: "6ySmhJd6qGUMCthiqszyb4Od4U6TFn0v3DLz-1EZrNQ",
 *         rawId: "eb24a684977aa8650c0ad862aaccf26f839de14e93167d2fdc32f3fb5119acd4",
 *         authenticatorAttachment: "platform",
 *         type: "public-key",
 *         response: {
 *             attestationObject: "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YViko3mm9u6vuaVeN4wRgDTidR5oL6ufLTCrE9ISVYbOGUdFAAAAAAAAAAAAAAAAAAAAAAAAAAAAIOskpoSXeqhlDArYYqrM8m-DneFOkxZ9L9wy8_tRGazUpQECAyYgASFYIOP8op-6gZJ1H0wHNLe2k7cgBqaSUR4pdcBqtOHPaYUhIlggsXZWuWfZS-6YpbeU9dsB2UoroACSKXJOrdE_auaUIf4",
 *             clientDataJson: "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiV1VZd05EaGtNV0UzWldNellUSmhOamszTURBMU9XTXlOelkyWW1Kak4yVXdaZyIsIm9yaWdpbiI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9",
 *             transports: ["internal"]
 *         }
 *     }
 */
export interface VerifyPasskeyFactorsRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** A [base64url](https://base64.guru/standards/base64url) encoded representation of `rawId`. */
    id?: string;
    /** The globally unique identifier for this `PublicKeyCredential`. */
    rawId?: string;
    /**
     * A string that indicates the mechanism by which the WebAuthn implementation is attached to the authenticator at the time the associated
     * `navigator.credentials.create()` or `navigator.credentials.get()` call completes.
     */
    authenticatorAttachment?: Twilio.VerifyPasskeyFactorsRequestAuthenticatorAttachment;
    /**
     * The valid credential types supported by the API.
     * The values of this enumeration are used for versioning the `AuthenticatorAssertion` and `AuthenticatorAttestation` structures according to the type of the authenticator.
     */
    type?: Twilio.VerifyPasskeyFactorsRequestType;
    /** The result of a WebAuthn credential registration via `navigator.credentials.create()`, as specified in [AuthenticatorAttestationResponse](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse). */
    response: Twilio.VerifyPasskeyFactorsRequestResponse;
}
