// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { VerificationEnumRiskCheck } from "../../../../types/VerificationEnumRiskCheck.js";

export const CreateVerificationsRequest: core.serialization.Schema<
    serializers.CreateVerificationsRequest.Raw,
    Omit<Twilio.CreateVerificationsRequest, "serviceSid">
> = core.serialization.object({
    to: core.serialization.property("To", core.serialization.string()),
    channel: core.serialization.property("Channel", core.serialization.string()),
    customFriendlyName: core.serialization.property("CustomFriendlyName", core.serialization.string().optional()),
    customMessage: core.serialization.property("CustomMessage", core.serialization.string().optional()),
    sendDigits: core.serialization.property("SendDigits", core.serialization.string().optional()),
    locale: core.serialization.property("Locale", core.serialization.string().optional()),
    customCode: core.serialization.property("CustomCode", core.serialization.string().optional()),
    amount: core.serialization.property("Amount", core.serialization.string().optional()),
    payee: core.serialization.property("Payee", core.serialization.string().optional()),
    rateLimits: core.serialization.property("RateLimits", core.serialization.unknown().optional()),
    channelConfiguration: core.serialization.property("ChannelConfiguration", core.serialization.unknown().optional()),
    appHash: core.serialization.property("AppHash", core.serialization.string().optional()),
    templateSid: core.serialization.property("TemplateSid", core.serialization.string().optional()),
    templateCustomSubstitutions: core.serialization.property(
        "TemplateCustomSubstitutions",
        core.serialization.string().optional(),
    ),
    deviceIp: core.serialization.property("DeviceIp", core.serialization.string().optional()),
    enableSnaClientToken: core.serialization.property("EnableSnaClientToken", core.serialization.boolean().optional()),
    riskCheck: core.serialization.property("RiskCheck", VerificationEnumRiskCheck.optional()),
    tags: core.serialization.property("Tags", core.serialization.string().optional()),
});

export declare namespace CreateVerificationsRequest {
    export interface Raw {
        To: string;
        Channel: string;
        CustomFriendlyName?: string | null;
        CustomMessage?: string | null;
        SendDigits?: string | null;
        Locale?: string | null;
        CustomCode?: string | null;
        Amount?: string | null;
        Payee?: string | null;
        RateLimits?: unknown | null;
        ChannelConfiguration?: unknown | null;
        AppHash?: string | null;
        TemplateSid?: string | null;
        TemplateCustomSubstitutions?: string | null;
        DeviceIp?: string | null;
        EnableSnaClientToken?: boolean | null;
        RiskCheck?: VerificationEnumRiskCheck.Raw | null;
        Tags?: string | null;
    }
}
