// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { VerificationEnumStatus } from "../../../../types/VerificationEnumStatus.js";

export const UpdateVerificationsRequest: core.serialization.Schema<
    serializers.UpdateVerificationsRequest.Raw,
    Omit<Twilio.UpdateVerificationsRequest, "serviceSid" | "sid">
> = core.serialization.object({
    status: core.serialization.property("Status", VerificationEnumStatus),
});

export declare namespace UpdateVerificationsRequest {
    export interface Raw {
        Status: VerificationEnumStatus.Raw;
    }
}
