// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { WebhookEnumStatus } from "../../../../types/WebhookEnumStatus.js";
import { WebhookEnumVersion } from "../../../../types/WebhookEnumVersion.js";

export const UpdateWebhooksRequest: core.serialization.Schema<
    serializers.UpdateWebhooksRequest.Raw,
    Omit<Twilio.UpdateWebhooksRequest, "serviceSid" | "sid">
> = core.serialization.object({
    friendlyName: core.serialization.property("FriendlyName", core.serialization.string().optional()),
    eventTypes: core.serialization.property(
        "EventTypes",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    webhookUrl: core.serialization.property("WebhookUrl", core.serialization.string().optional()),
    status: core.serialization.property("Status", WebhookEnumStatus.optional()),
    version: core.serialization.property("Version", WebhookEnumVersion.optional()),
});

export declare namespace UpdateWebhooksRequest {
    export interface Raw {
        FriendlyName?: string | null;
        EventTypes?: string[] | null;
        WebhookUrl?: string | null;
        Status?: WebhookEnumStatus.Raw | null;
        Version?: WebhookEnumVersion.Raw | null;
    }
}
