// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { ApprovePasskeyChallengesRequestAuthenticatorAttachment } from "../../types/ApprovePasskeyChallengesRequestAuthenticatorAttachment.js";
import { ApprovePasskeyChallengesRequestResponse } from "../../types/ApprovePasskeyChallengesRequestResponse.js";
import { ApprovePasskeyChallengesRequestType } from "../../types/ApprovePasskeyChallengesRequestType.js";

export const ApprovePasskeyChallengesRequest: core.serialization.Schema<
    serializers.ApprovePasskeyChallengesRequest.Raw,
    Omit<Twilio.ApprovePasskeyChallengesRequest, "serviceSid">
> = core.serialization.object({
    id: core.serialization.string(),
    rawId: core.serialization.string(),
    authenticatorAttachment: ApprovePasskeyChallengesRequestAuthenticatorAttachment,
    type: ApprovePasskeyChallengesRequestType.optional(),
    response: ApprovePasskeyChallengesRequestResponse,
});

export declare namespace ApprovePasskeyChallengesRequest {
    export interface Raw {
        id: string;
        rawId: string;
        authenticatorAttachment: ApprovePasskeyChallengesRequestAuthenticatorAttachment.Raw;
        type?: ApprovePasskeyChallengesRequestType.Raw | null;
        response: ApprovePasskeyChallengesRequestResponse.Raw;
    }
}
