// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateChallengesRequest: core.serialization.Schema<
    serializers.CreateChallengesRequest.Raw,
    Omit<Twilio.CreateChallengesRequest, "serviceSid" | "identity">
> = core.serialization.object({
    factorSid: core.serialization.property("FactorSid", core.serialization.string()),
    expirationDate: core.serialization.property("ExpirationDate", core.serialization.date().optional()),
    detailsMessage: core.serialization.property("Details.Message", core.serialization.string().optional()),
    detailsFields: core.serialization.property(
        "Details.Fields",
        core.serialization.list(core.serialization.unknown()).optional(),
    ),
    hiddenDetails: core.serialization.property("HiddenDetails", core.serialization.unknown().optional()),
    authPayload: core.serialization.property("AuthPayload", core.serialization.string().optional()),
});

export declare namespace CreateChallengesRequest {
    export interface Raw {
        FactorSid: string;
        ExpirationDate?: string | null;
        "Details.Message"?: string | null;
        "Details.Fields"?: unknown[] | null;
        HiddenDetails?: unknown | null;
        AuthPayload?: string | null;
    }
}
