// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreatePasskeyChallengesRequest: core.serialization.Schema<
    serializers.CreatePasskeyChallengesRequest.Raw,
    Omit<Twilio.CreatePasskeyChallengesRequest, "serviceSid">
> = core.serialization.object({
    identity: core.serialization.string().optional(),
    factorSid: core.serialization.property("factor_sid", core.serialization.string().optional()),
});

export declare namespace CreatePasskeyChallengesRequest {
    export interface Raw {
        identity?: string | null;
        factor_sid?: string | null;
    }
}
