// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateChallengesRequest: core.serialization.Schema<
    serializers.UpdateChallengesRequest.Raw,
    Omit<Twilio.UpdateChallengesRequest, "serviceSid" | "identity" | "sid">
> = core.serialization.object({
    authPayload: core.serialization.property("AuthPayload", core.serialization.string().optional()),
    metadata: core.serialization.property("Metadata", core.serialization.unknown().optional()),
});

export declare namespace UpdateChallengesRequest {
    export interface Raw {
        AuthPayload?: string | null;
        Metadata?: unknown | null;
    }
}
