// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         formType: "form-push"
 *     }
 */
export interface FetchFormsRequest {
    /** The Type of this Form. Currently only `form-push` is supported. */
    formType: Twilio.FormEnumFormTypes;
}
