// This file was auto-generated by Fern from our API Definition.

/** A string that indicates the mechanism by which the WebAuthn implementation is attached to the authenticator at the time the associated `navigator.credentials.create()` or `navigator.credentials.get()` call completes. */
export const ApprovePasskeyChallengesRequestAuthenticatorAttachment = {
    Platform: "platform",
    CrossPlatform: "cross-platform",
} as const;
export type ApprovePasskeyChallengesRequestAuthenticatorAttachment =
    (typeof ApprovePasskeyChallengesRequestAuthenticatorAttachment)[keyof typeof ApprovePasskeyChallengesRequestAuthenticatorAttachment];
