// This file was auto-generated by Fern from our API Definition.

/** The Status of this Challenge. One of `pending`, `expired`, `approved` or `denied`. */
export const ApprovePasskeyChallengesResponseStatus = {
    Pending: "pending",
    Expired: "expired",
    Approved: "approved",
    Denied: "denied",
} as const;
export type ApprovePasskeyChallengesResponseStatus =
    (typeof ApprovePasskeyChallengesResponseStatus)[keyof typeof ApprovePasskeyChallengesResponseStatus];
