// This file was auto-generated by Fern from our API Definition.

/**
 * The result of a WebAuthn authentication via a `navigator.credentials.get()` request, as specified in [AuthenticatorAttestationResponse](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse).
 */
export interface ApprovePasskeyChallengesRequestResponse {
    /** The [authenticator data](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API/Authenticator_data) structure contains information from the authenticator about the processing of a credential creation or authentication request. */
    authenticatorData: string;
    /** This property contains the JSON-compatible serialization of the data passed from the browser to the authenticator in order to generate this credential. */
    clientDataJson: string;
    /** An assertion signature over `authenticatorData` and `clientDataJSON`. The assertion signature is created with the private key of the key pair that was created during the originating `navigator.credentials.create()` call and verified using the public key of that same key pair. */
    signature: string;
    /** The user handle stored in the authenticator, specified as `user.id` in the options passed to the originating `navigator.credentials.create()` call. This property should contain a base64url-encoded entity SID. */
    userHandle?: string;
}
