// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface CreatePasskeyChallengesResponse {
    /** An object that contains challenge options. Currently only used for `passkeys`. */
    options?: Record<string, unknown>;
    /** A 34 character string that uniquely identifies this Challenge. */
    sid?: string | null;
    /** The unique SID identifier of the Account. */
    accountSid?: string | null;
    /** The unique SID identifier of the Service. */
    serviceSid?: string | null;
    /** The unique SID identifier of the Entity. */
    entitySid?: string | null;
    /** Customer unique identity for the Entity owner of the Challenge. */
    identity?: string | null;
    /** The unique SID identifier of the Factor. */
    factorSid?: string | null;
    /** The date that this Challenge was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateCreated?: Date | null;
    /** The date that this Challenge was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateUpdated?: Date | null;
    /** The date that this Challenge was responded, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateResponded?: Date | null;
    /** The date-time when this Challenge expires, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    expirationDate?: Date | null;
    /** The Status of this Challenge. One of `pending`, `expired`, `approved` or `denied`. */
    status?: Twilio.CreatePasskeyChallengesResponseStatus;
    /** Reason for the Challenge to be in certain `status`. One of `none`, `not_needed` or `not_requested`. */
    respondedReason?: Twilio.CreatePasskeyChallengesResponseRespondedReason;
    /** Details provided to give context about the Challenge. */
    details?: unknown | null;
    /** Details provided to give context about the Challenge. */
    hiddenDetails?: unknown | null;
    /** Custom metadata associated with the challenge. */
    metadata?: unknown | null;
    /** The Factor Type of this Challenge. Currently `push` and `totp` are supported. */
    factorType?: Twilio.CreatePasskeyChallengesResponseFactorType;
    /** The URL of this resource. */
    url?: string | null;
    /** Contains a dictionary of URL links to nested resources of this Challenge. */
    links?: Record<string, unknown> | null;
}
