// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListChallengesResponse {
    challenges?: Twilio.VerifyV2ServiceEntityChallenge[];
    meta?: Twilio.ListChallengesResponseMeta;
}
