// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2ServiceRateLimit } from "../../../types/VerifyV2ServiceRateLimit.js";
import { ListRateLimitsResponseMeta } from "./ListRateLimitsResponseMeta.js";

export const ListRateLimitsResponse: core.serialization.ObjectSchema<
    serializers.ListRateLimitsResponse.Raw,
    Twilio.ListRateLimitsResponse
> = core.serialization.object({
    rateLimits: core.serialization.property(
        "rate_limits",
        core.serialization.list(VerifyV2ServiceRateLimit).optional(),
    ),
    meta: ListRateLimitsResponseMeta.optional(),
});

export declare namespace ListRateLimitsResponse {
    export interface Raw {
        rate_limits?: VerifyV2ServiceRateLimit.Raw[] | null;
        meta?: ListRateLimitsResponseMeta.Raw | null;
    }
}
