// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sid: "Sid"
 *     }
 */
export interface FetchVerificationAttemptsRequest {
    /** The unique SID identifier of a Verification Attempt */
    sid: string;
}
