// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         verifyServiceSid: "VAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 *         dateCreatedAfter: new Date("2022-03-02T21:02:33.000Z"),
 *         dateCreatedBefore: new Date("2022-03-02T21:02:33.000Z"),
 *         country: "CO",
 *         destinationPrefix: "+57305"
 *     }
 */
export interface FetchSummaryVerificationAttemptsRequest {
    /** Filter used to consider only Verification Attempts of the given verify service on the summary aggregation. */
    verifyServiceSid?: string;
    /** Datetime filter used to consider only Verification Attempts created after this datetime on the summary aggregation. Given as GMT in ISO 8601 formatted datetime string: yyyy-MM-dd'T'HH:mm:ss'Z. */
    dateCreatedAfter?: Date;
    /** Datetime filter used to consider only Verification Attempts created before this datetime on the summary aggregation. Given as GMT in ISO 8601 formatted datetime string: yyyy-MM-dd'T'HH:mm:ss'Z. */
    dateCreatedBefore?: Date;
    /** Filter used to consider only Verification Attempts sent to the specified destination country on the summary aggregation. */
    country?: string;
    /** Filter Verification Attempts considered on the summary aggregation by communication channel. */
    channel?: Twilio.VerificationAttemptsSummaryEnumChannels;
    /** Filter the Verification Attempts considered on the summary aggregation by Destination prefix. It is the prefix of a phone number in E.164 format. */
    destinationPrefix?: string;
}
