// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateEntitiesRequest: core.serialization.Schema<
    serializers.CreateEntitiesRequest.Raw,
    Omit<Twilio.CreateEntitiesRequest, "serviceSid">
> = core.serialization.object({
    identity: core.serialization.property("Identity", core.serialization.string()),
});

export declare namespace CreateEntitiesRequest {
    export interface Raw {
        Identity: string;
    }
}
