// This file was auto-generated by Fern from our API Definition.

import { AccessTokensClient } from "./api/resources/accessTokens/client/Client.js";
import { BucketsClient } from "./api/resources/buckets/client/Client.js";
import { ChallengesClient } from "./api/resources/challenges/client/Client.js";
import { EntitiesClient } from "./api/resources/entities/client/Client.js";
import { FactorsClient } from "./api/resources/factors/client/Client.js";
import { FormsClient } from "./api/resources/forms/client/Client.js";
import { MessagingConfigurationsClient } from "./api/resources/messagingConfigurations/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { RateLimitsClient } from "./api/resources/rateLimits/client/Client.js";
import { SafelistClient } from "./api/resources/safelist/client/Client.js";
import { ServicesClient } from "./api/resources/services/client/Client.js";
import { TemplatesClient } from "./api/resources/templates/client/Client.js";
import { VerificationAttemptsClient } from "./api/resources/verificationAttempts/client/Client.js";
import { VerificationChecksClient } from "./api/resources/verificationChecks/client/Client.js";
import { VerificationsClient } from "./api/resources/verifications/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace TwilioClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TwilioClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TwilioClient.Options>;
    protected _accessTokens: AccessTokensClient | undefined;
    protected _buckets: BucketsClient | undefined;
    protected _challenges: ChallengesClient | undefined;
    protected _entities: EntitiesClient | undefined;
    protected _factors: FactorsClient | undefined;
    protected _forms: FormsClient | undefined;
    protected _messagingConfigurations: MessagingConfigurationsClient | undefined;
    protected _notifications: NotificationsClient | undefined;
    protected _rateLimits: RateLimitsClient | undefined;
    protected _safelist: SafelistClient | undefined;
    protected _services: ServicesClient | undefined;
    protected _verifications: VerificationsClient | undefined;
    protected _verificationAttempts: VerificationAttemptsClient | undefined;
    protected _verificationChecks: VerificationChecksClient | undefined;
    protected _templates: TemplatesClient | undefined;
    protected _webhooks: WebhooksClient | undefined;

    constructor(options: TwilioClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get accessTokens(): AccessTokensClient {
        return (this._accessTokens ??= new AccessTokensClient(this._options));
    }

    public get buckets(): BucketsClient {
        return (this._buckets ??= new BucketsClient(this._options));
    }

    public get challenges(): ChallengesClient {
        return (this._challenges ??= new ChallengesClient(this._options));
    }

    public get entities(): EntitiesClient {
        return (this._entities ??= new EntitiesClient(this._options));
    }

    public get factors(): FactorsClient {
        return (this._factors ??= new FactorsClient(this._options));
    }

    public get forms(): FormsClient {
        return (this._forms ??= new FormsClient(this._options));
    }

    public get messagingConfigurations(): MessagingConfigurationsClient {
        return (this._messagingConfigurations ??= new MessagingConfigurationsClient(this._options));
    }

    public get notifications(): NotificationsClient {
        return (this._notifications ??= new NotificationsClient(this._options));
    }

    public get rateLimits(): RateLimitsClient {
        return (this._rateLimits ??= new RateLimitsClient(this._options));
    }

    public get safelist(): SafelistClient {
        return (this._safelist ??= new SafelistClient(this._options));
    }

    public get services(): ServicesClient {
        return (this._services ??= new ServicesClient(this._options));
    }

    public get verifications(): VerificationsClient {
        return (this._verifications ??= new VerificationsClient(this._options));
    }

    public get verificationAttempts(): VerificationAttemptsClient {
        return (this._verificationAttempts ??= new VerificationAttemptsClient(this._options));
    }

    public get verificationChecks(): VerificationChecksClient {
        return (this._verificationChecks ??= new VerificationChecksClient(this._options));
    }

    public get templates(): TemplatesClient {
        return (this._templates ??= new TemplatesClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
