// This file was auto-generated by Fern from our API Definition.

export const TwilioEnvironment = {
    Default: "https://verify.twilio.com",
} as const;

export type TwilioEnvironment = typeof TwilioEnvironment.Default;
