// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         rateLimitSid: "RateLimitSid",
 *         sid: "Sid"
 *     }
 */
export interface DeleteBucketsRequest {
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with. */
    serviceSid: string;
    /** The Twilio-provided string that uniquely identifies the Rate Limit resource. */
    rateLimitSid: string;
    /** A 34 character string that uniquely identifies this Bucket. */
    sid: string;
}
