// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         rateLimitSid: "RateLimitSid"
 *     }
 */
export interface ListBucketsRequest {
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with. */
    serviceSid: string;
    /** The Twilio-provided string that uniquely identifies the Rate Limit resource. */
    rateLimitSid: string;
    /** How many resources to return in each list page. The default is 50, and the maximum is 1000. */
    pageSize?: number;
    /** The page index. This value is simply for client state. */
    page?: number;
    /** The page token. This is provided by the API. */
    pageToken?: string;
}
