// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         rateLimitSid: "RateLimitSid",
 *         sid: "Sid",
 *         max: 5,
 *         interval: 60
 *     }
 */
export interface UpdateBucketsRequest {
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with. */
    serviceSid: string;
    /** The Twilio-provided string that uniquely identifies the Rate Limit resource. */
    rateLimitSid: string;
    /** A 34 character string that uniquely identifies this Bucket. */
    sid: string;
    /** Maximum number of requests permitted in during the interval. */
    max?: number;
    /** Number of seconds that the rate limit will be enforced over. */
    interval?: number;
}
