// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateBucketsRequest: core.serialization.Schema<
    serializers.CreateBucketsRequest.Raw,
    Omit<Twilio.CreateBucketsRequest, "serviceSid" | "rateLimitSid">
> = core.serialization.object({
    max: core.serialization.property("Max", core.serialization.number()),
    interval: core.serialization.property("Interval", core.serialization.number()),
});

export declare namespace CreateBucketsRequest {
    export interface Raw {
        Max: number;
        Interval: number;
    }
}
