// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateBucketsRequest: core.serialization.Schema<
    serializers.UpdateBucketsRequest.Raw,
    Omit<Twilio.UpdateBucketsRequest, "serviceSid" | "rateLimitSid" | "sid">
> = core.serialization.object({
    max: core.serialization.property("Max", core.serialization.number().optional()),
    interval: core.serialization.property("Interval", core.serialization.number().optional()),
});

export declare namespace UpdateBucketsRequest {
    export interface Raw {
        Max?: number | null;
        Interval?: number | null;
    }
}
