// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateVerificationChecksRequest: core.serialization.Schema<
    serializers.CreateVerificationChecksRequest.Raw,
    Omit<Twilio.CreateVerificationChecksRequest, "serviceSid">
> = core.serialization.object({
    code: core.serialization.property("Code", core.serialization.string().optional()),
    to: core.serialization.property("To", core.serialization.string().optional()),
    verificationSid: core.serialization.property("VerificationSid", core.serialization.string().optional()),
    amount: core.serialization.property("Amount", core.serialization.string().optional()),
    payee: core.serialization.property("Payee", core.serialization.string().optional()),
    snaClientToken: core.serialization.property("SnaClientToken", core.serialization.string().optional()),
});

export declare namespace CreateVerificationChecksRequest {
    export interface Raw {
        Code?: string | null;
        To?: string | null;
        VerificationSid?: string | null;
        Amount?: string | null;
        Payee?: string | null;
        SnaClientToken?: string | null;
    }
}
