// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateSafelistRequest: core.serialization.Schema<
    serializers.CreateSafelistRequest.Raw,
    Twilio.CreateSafelistRequest
> = core.serialization.object({
    phoneNumber: core.serialization.property("PhoneNumber", core.serialization.string()),
});

export declare namespace CreateSafelistRequest {
    export interface Raw {
        PhoneNumber: string;
    }
}
