// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity"
 *     }
 */
export interface FetchEntitiesRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** The unique external identifier for the Entity of the Service. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity: string;
}
