// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "ff483d1ff591898a9942916050d2ca3f",
 *         factorType: "push",
 *         factorFriendlyName: "John Doe iPhone",
 *         ttl: 300
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "ff483d1ff591898a9942916050d2ca3f",
 *         factorType: "push",
 *         factorFriendlyName: "John Doe iPhone"
 *     }
 */
export interface CreateAccessTokensRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** The unique external identifier for the Entity of the Service. This identifier should be immutable, not PII, and generated by your external system, such as your user's UUID, GUID, or SID. */
    identity: string;
    factorType: Twilio.AccessTokenEnumFactorTypes;
    /** The friendly name of the factor that is going to be created with this access token */
    factorFriendlyName?: string;
    /** How long, in seconds, the access token is valid. Can be an integer between 60 and 300. Default is 60. */
    ttl?: number;
}
