// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         sid: "Sid"
 *     }
 */
export interface FetchAccessTokensRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** A 34 character string that uniquely identifies this Access Token. */
    sid: string;
}
