// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         id: "6ySmhJd6qGUMCthiqszyb4Od4U6TFn0v3DLz-1EZrNQ",
 *         rawId: "eb24a684977aa8650c0ad862aaccf26f839de14e93167d2fdc32f3fb5119acd4",
 *         authenticatorAttachment: "platform",
 *         type: "public-key",
 *         response: {
 *             authenticatorData: "o3mm9u6vuaVeN4wRgDTid",
 *             clientDataJson: "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiV1VZd05EaGtNV0UzWldNellUSmhOamszTURBMU9XTXlOelkyWW1Kak4yVXdaZyIsIm9yaWdpbiI6Imh0dHBzOi8vZXhhbXBsZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9",
 *             signature: "MEYCIQDDs662ykELzpmxkQaOR6HY5GwO7n",
 *             userHandle: "WUU0ZmQzYWFmNGU0NT"
 *         }
 *     }
 */
export interface ApprovePasskeyChallengesRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** A [base64url](https://base64.guru/standards/base64url) encoded representation of `rawId`. */
    id: string;
    /** The globally unique identifier for this `PublicKeyCredential`. */
    rawId: string;
    /** A string that indicates the mechanism by which the WebAuthn implementation is attached to the authenticator at the time the associated `navigator.credentials.create()` or `navigator.credentials.get()` call completes. */
    authenticatorAttachment: Twilio.ApprovePasskeyChallengesRequestAuthenticatorAttachment;
    /** The valid credential types supported by the API. The values of this enumeration are used for versioning the `AuthenticatorAssertion` and `AuthenticatorAttestation` structures according to the type of the authenticator. */
    type?: Twilio.ApprovePasskeyChallengesRequestType;
    /** The result of a WebAuthn authentication via a `navigator.credentials.get()` request, as specified in [AuthenticatorAttestationResponse](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse). */
    response: Twilio.ApprovePasskeyChallengesRequestResponse;
}
