// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         factorSid: "YF03aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 *         expirationDate: new Date("2015-07-30T20:00:00.000Z"),
 *         detailsMessage: "Hi! Mr. John Doe, would you like to sign up?",
 *         detailsFields: ["{\"label\": \"Action\", \"value\": \"Sign up in portal\"}"],
 *         hiddenDetails: "{\"ip\": \"172.168.1.234\"}"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         factorSid: "YF02aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 *         expirationDate: new Date("2015-07-30T20:00:00.000Z"),
 *         detailsMessage: "Hi! Mr. John Doe, would you like to sign up?",
 *         detailsFields: ["{\"label\": \"Action\", \"value\": \"Sign up in portal\"}"],
 *         hiddenDetails: "{\"ip\": \"172.168.1.234\"}"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         factorSid: "YF02aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 *         expirationDate: new Date("2015-07-30T20:00:00.000Z"),
 *         detailsMessage: "Hi! Mr. John Doe, would you like to sign up?",
 *         detailsFields: ["{\"label\": \"Action\", \"value\": \"Sign up in portal\"}"],
 *         hiddenDetails: "{\"ip\": \"172.168.1.234\"}",
 *         authPayload: "12345678"
 *     }
 */
export interface CreateChallengesRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity: string;
    /** The unique SID identifier of the Factor. */
    factorSid: string;
    /** The date-time when this Challenge expires, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. The default value is five (5) minutes after Challenge creation. The max value is sixty (60) minutes after creation. */
    expirationDate?: Date;
    /** Shown to the user when the push notification arrives. Required when `factor_type` is `push`. Can be up to 256 characters in length */
    detailsMessage?: string;
    /** A list of objects that describe the Fields included in the Challenge. Each object contains the label and value of the field, the label can be up to 36 characters in length and the value can be up to 128 characters in length. Used when `factor_type` is `push`. There can be up to 20 details fields. */
    detailsFields?: unknown[];
    /** Details provided to give context about the Challenge. Not shown to the end user. It must be a stringified JSON with only strings values eg. `{"ip": "172.168.1.234"}`. Can be up to 1024 characters in length */
    hiddenDetails?: unknown;
    /** Optional payload used to verify the Challenge upon creation. Only used with a Factor of type `totp` to carry the TOTP code that needs to be verified. For `TOTP` this value must be between 3 and 8 characters long. */
    authPayload?: string;
}
