// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "anyUUID"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "anyUUID",
 *         factorSid: "YFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
 *     }
 */
export interface CreatePasskeyChallengesRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    identity?: string;
    factorSid?: string;
}
