// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity",
 *         sid: "Sid"
 *     }
 */
export interface FetchChallengesRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** Customer unique identity for the Entity owner of the Challenges. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity: string;
    /** A 34 character string that uniquely identifies this Challenge. */
    sid: string;
}
