// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         identity: "Identity"
 *     }
 */
export interface ListChallengesRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters. */
    identity: string;
    /** The unique SID identifier of the Factor. */
    factorSid?: string;
    /** The Status of the Challenges to fetch. One of `pending`, `expired`, `approved` or `denied`. */
    status?: Twilio.ChallengeEnumChallengeStatuses;
    /** The desired sort order of the Challenges list. One of `asc` or `desc` for ascending and descending respectively. Defaults to `asc`. */
    order?: Twilio.ChallengeEnumListOrders;
    /** How many resources to return in each list page. The default is 50, and the maximum is 1000. */
    pageSize?: number;
    /** The page index. This value is simply for client state. */
    page?: number;
    /** The page token. This is provided by the API. */
    pageToken?: string;
}
