// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         uniqueName: "unique.name",
 *         description: "Description"
 *     }
 */
export interface CreateRateLimitsRequest {
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with. */
    serviceSid: string;
    /** Provides a unique and addressable name to be assigned to this Rate Limit, assigned by the developer, to be optionally used in addition to SID. **This value should not contain PII.** */
    uniqueName: string;
    /** Description of this Rate Limit */
    description?: string;
}
