// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         sid: "Sid"
 *     }
 */
export interface FetchRateLimitsRequest {
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with. */
    serviceSid: string;
    /** The Twilio-provided string that uniquely identifies the Rate Limit resource to fetch. */
    sid: string;
}
