// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         country: "Country"
 *     }
 */
export interface FetchMessagingConfigurationsRequest {
    /** The SID of the [Service](https://www.twilio.com/docs/verify/api/service) that the resource is associated with. */
    serviceSid: string;
    /** The [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code of the country this configuration will be applied to. If this is a global configuration, Country will take the value `all`. */
    country: string;
}
