// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2ServiceWebhook } from "../../../types/VerifyV2ServiceWebhook.js";
import { ListWebhooksResponseMeta } from "./ListWebhooksResponseMeta.js";

export const ListWebhooksResponse: core.serialization.ObjectSchema<
    serializers.ListWebhooksResponse.Raw,
    Twilio.ListWebhooksResponse
> = core.serialization.object({
    webhooks: core.serialization.list(VerifyV2ServiceWebhook).optional(),
    meta: ListWebhooksResponseMeta.optional(),
});

export declare namespace ListWebhooksResponse {
    export interface Raw {
        webhooks?: VerifyV2ServiceWebhook.Raw[] | null;
        meta?: ListWebhooksResponseMeta.Raw | null;
    }
}
