// This file was auto-generated by Fern from our API Definition.

export interface ListVerificationAttemptsResponseMeta {
    firstPageUrl?: string;
    key?: string;
    nextPageUrl?: string | null;
    page?: number;
    pageSize?: number;
    previousPageUrl?: string | null;
    url?: string;
}
