// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListVerificationAttemptsResponse {
    attempts?: Twilio.VerifyV2VerificationAttempt[];
    meta?: Twilio.ListVerificationAttemptsResponseMeta;
}
