// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2ServiceEntity } from "../../../types/VerifyV2ServiceEntity.js";
import { ListEntitiesResponseMeta } from "./ListEntitiesResponseMeta.js";

export const ListEntitiesResponse: core.serialization.ObjectSchema<
    serializers.ListEntitiesResponse.Raw,
    Twilio.ListEntitiesResponse
> = core.serialization.object({
    entities: core.serialization.list(VerifyV2ServiceEntity).optional(),
    meta: ListEntitiesResponseMeta.optional(),
});

export declare namespace ListEntitiesResponse {
    export interface Raw {
        entities?: VerifyV2ServiceEntity.Raw[] | null;
        meta?: ListEntitiesResponseMeta.Raw | null;
    }
}
