// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AccessTokenEnumFactorTypes: core.serialization.Schema<
    serializers.AccessTokenEnumFactorTypes.Raw,
    Twilio.AccessTokenEnumFactorTypes
> = core.serialization.enum_(["push"]);

export declare namespace AccessTokenEnumFactorTypes {
    export type Raw = "push";
}
