// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChallengeEnumChallengeStatuses: core.serialization.Schema<
    serializers.ChallengeEnumChallengeStatuses.Raw,
    Twilio.ChallengeEnumChallengeStatuses
> = core.serialization.enum_(["pending", "expired", "approved", "denied"]);

export declare namespace ChallengeEnumChallengeStatuses {
    export type Raw = "pending" | "expired" | "approved" | "denied";
}
