// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChallengeEnumListOrders: core.serialization.Schema<
    serializers.ChallengeEnumListOrders.Raw,
    Twilio.ChallengeEnumListOrders
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace ChallengeEnumListOrders {
    export type Raw = "asc" | "desc";
}
