// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FactorEnumTotpAlgorithms: core.serialization.Schema<
    serializers.FactorEnumTotpAlgorithms.Raw,
    Twilio.FactorEnumTotpAlgorithms
> = core.serialization.enum_(["sha1", "sha256", "sha512"]);

export declare namespace FactorEnumTotpAlgorithms {
    export type Raw = "sha1" | "sha256" | "sha512";
}
