// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FactorEnumNotificationPlatforms: core.serialization.Schema<
    serializers.FactorEnumNotificationPlatforms.Raw,
    Twilio.FactorEnumNotificationPlatforms
> = core.serialization.enum_(["apn", "fcm", "none"]);

export declare namespace FactorEnumNotificationPlatforms {
    export type Raw = "apn" | "fcm" | "none";
}
