// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FactorEnumFactorStatuses: core.serialization.Schema<
    serializers.FactorEnumFactorStatuses.Raw,
    Twilio.FactorEnumFactorStatuses
> = core.serialization.enum_(["unverified", "verified"]);

export declare namespace FactorEnumFactorStatuses {
    export type Raw = "unverified" | "verified";
}
