// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FormEnumFormTypes: core.serialization.Schema<serializers.FormEnumFormTypes.Raw, Twilio.FormEnumFormTypes> =
    core.serialization.enum_(["form-push"]);

export declare namespace FormEnumFormTypes {
    export type Raw = "form-push";
}
