// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const NewFactorEnumFactorStatuses: core.serialization.Schema<
    serializers.NewFactorEnumFactorStatuses.Raw,
    Twilio.NewFactorEnumFactorStatuses
> = core.serialization.enum_(["unverified", "verified"]);

export declare namespace NewFactorEnumFactorStatuses {
    export type Raw = "unverified" | "verified";
}
