// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const NewFactorEnumNotificationPlatforms: core.serialization.Schema<
    serializers.NewFactorEnumNotificationPlatforms.Raw,
    Twilio.NewFactorEnumNotificationPlatforms
> = core.serialization.enum_(["apn", "fcm", "none"]);

export declare namespace NewFactorEnumNotificationPlatforms {
    export type Raw = "apn" | "fcm" | "none";
}
