// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const NewFactorEnumTotpAlgorithms: core.serialization.Schema<
    serializers.NewFactorEnumTotpAlgorithms.Raw,
    Twilio.NewFactorEnumTotpAlgorithms
> = core.serialization.enum_(["sha1", "sha256", "sha512"]);

export declare namespace NewFactorEnumTotpAlgorithms {
    export type Raw = "sha1" | "sha256" | "sha512";
}
