// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TooManyRequestsErrorBody: core.serialization.ObjectSchema<
    serializers.TooManyRequestsErrorBody.Raw,
    Twilio.TooManyRequestsErrorBody
> = core.serialization.object({
    code: core.serialization.number().optional(),
    message: core.serialization.string().optional(),
    moreInfo: core.serialization.property("more_info", core.serialization.string().optional()),
    status: core.serialization.number().optional(),
});

export declare namespace TooManyRequestsErrorBody {
    export interface Raw {
        code?: number | null;
        message?: string | null;
        more_info?: string | null;
        status?: number | null;
    }
}
