// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2VerificationTemplate: core.serialization.ObjectSchema<
    serializers.VerifyV2VerificationTemplate.Raw,
    Twilio.VerifyV2VerificationTemplate
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    friendlyName: core.serialization.property("friendly_name", core.serialization.string().optionalNullable()),
    channels: core.serialization.list(core.serialization.string()).optionalNullable(),
    translations: core.serialization.unknown().optionalNullable(),
});

export declare namespace VerifyV2VerificationTemplate {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        friendly_name?: (string | null | undefined) | null;
        channels?: (string[] | null | undefined) | null;
        translations?: (unknown | null | undefined) | null;
    }
}
