// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { VerificationAttemptEnumChannels } from "./VerificationAttemptEnumChannels.js";
import { VerificationAttemptEnumConversionStatus } from "./VerificationAttemptEnumConversionStatus.js";

export const VerifyV2VerificationAttempt: core.serialization.ObjectSchema<
    serializers.VerifyV2VerificationAttempt.Raw,
    Twilio.VerifyV2VerificationAttempt
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    verificationSid: core.serialization.property("verification_sid", core.serialization.string().optionalNullable()),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    conversionStatus: core.serialization.property(
        "conversion_status",
        VerificationAttemptEnumConversionStatus.optional(),
    ),
    channel: VerificationAttemptEnumChannels.optional(),
    price: core.serialization.unknown().optionalNullable(),
    channelData: core.serialization.property("channel_data", core.serialization.unknown().optionalNullable()),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyV2VerificationAttempt {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        verification_sid?: (string | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        conversion_status?: VerificationAttemptEnumConversionStatus.Raw | null;
        channel?: VerificationAttemptEnumChannels.Raw | null;
        price?: (unknown | null | undefined) | null;
        channel_data?: (unknown | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
