// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerificationEnumStatus: core.serialization.Schema<
    serializers.VerificationEnumStatus.Raw,
    Twilio.VerificationEnumStatus
> = core.serialization.enum_(["canceled", "approved"]);

export declare namespace VerificationEnumStatus {
    export type Raw = "canceled" | "approved";
}
