// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { VerificationCheckEnumChannel } from "./VerificationCheckEnumChannel.js";

export const VerifyV2ServiceVerificationCheck: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceVerificationCheck.Raw,
    Twilio.VerifyV2ServiceVerificationCheck
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    to: core.serialization.string().optionalNullable(),
    channel: VerificationCheckEnumChannel.optional(),
    status: core.serialization.string().optionalNullable(),
    valid: core.serialization.boolean().optionalNullable(),
    amount: core.serialization.string().optionalNullable(),
    payee: core.serialization.string().optionalNullable(),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    snaAttemptsErrorCodes: core.serialization.property(
        "sna_attempts_error_codes",
        core.serialization.list(core.serialization.unknown()).optionalNullable(),
    ),
});

export declare namespace VerifyV2ServiceVerificationCheck {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        to?: (string | null | undefined) | null;
        channel?: VerificationCheckEnumChannel.Raw | null;
        status?: (string | null | undefined) | null;
        valid?: (boolean | null | undefined) | null;
        amount?: (string | null | undefined) | null;
        payee?: (string | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        sna_attempts_error_codes?: (unknown[] | null | undefined) | null;
    }
}
