// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerificationEnumRiskCheck: core.serialization.Schema<
    serializers.VerificationEnumRiskCheck.Raw,
    Twilio.VerificationEnumRiskCheck
> = core.serialization.enum_(["enable", "disable"]);

export declare namespace VerificationEnumRiskCheck {
    export type Raw = "enable" | "disable";
}
