// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2ServiceRateLimitBucket: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceRateLimitBucket.Raw,
    Twilio.VerifyV2ServiceRateLimitBucket
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    rateLimitSid: core.serialization.property("rate_limit_sid", core.serialization.string().optionalNullable()),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    max: core.serialization.number().optional(),
    interval: core.serialization.number().optional(),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyV2ServiceRateLimitBucket {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        rate_limit_sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        max?: number | null;
        interval?: number | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
