// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2ServiceRateLimit: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceRateLimit.Raw,
    Twilio.VerifyV2ServiceRateLimit
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    uniqueName: core.serialization.property("unique_name", core.serialization.string().optionalNullable()),
    description: core.serialization.string().optionalNullable(),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    url: core.serialization.string().optionalNullable(),
    links: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
});

export declare namespace VerifyV2ServiceRateLimit {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        unique_name?: (string | null | undefined) | null;
        description?: (string | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
        links?: (Record<string, unknown> | null | undefined) | null;
    }
}
