// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerificationAttemptEnumConversionStatus: core.serialization.Schema<
    serializers.VerificationAttemptEnumConversionStatus.Raw,
    Twilio.VerificationAttemptEnumConversionStatus
> = core.serialization.enum_(["converted", "unconverted"]);

export declare namespace VerificationAttemptEnumConversionStatus {
    export type Raw = "converted" | "unconverted";
}
