// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerificationAttemptEnumCallStatus: core.serialization.Schema<
    serializers.VerificationAttemptEnumCallStatus.Raw,
    Twilio.VerificationAttemptEnumCallStatus
> = core.serialization.enum_([
    "queued",
    "in-progress",
    "completed",
    "busy",
    "failed",
    "no-answer",
    "ringing",
    "canceled",
]);

export declare namespace VerificationAttemptEnumCallStatus {
    export type Raw = "queued" | "in-progress" | "completed" | "busy" | "failed" | "no-answer" | "ringing" | "canceled";
}
