// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2Service: core.serialization.ObjectSchema<serializers.VerifyV2Service.Raw, Twilio.VerifyV2Service> =
    core.serialization.object({
        sid: core.serialization.string().optionalNullable(),
        accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
        friendlyName: core.serialization.property("friendly_name", core.serialization.string().optionalNullable()),
        codeLength: core.serialization.property("code_length", core.serialization.number().optional()),
        lookupEnabled: core.serialization.property("lookup_enabled", core.serialization.boolean().optionalNullable()),
        psd2Enabled: core.serialization.property("psd2_enabled", core.serialization.boolean().optionalNullable()),
        skipSmsToLandlines: core.serialization.property(
            "skip_sms_to_landlines",
            core.serialization.boolean().optionalNullable(),
        ),
        dtmfInputRequired: core.serialization.property(
            "dtmf_input_required",
            core.serialization.boolean().optionalNullable(),
        ),
        ttsName: core.serialization.property("tts_name", core.serialization.string().optionalNullable()),
        doNotShareWarningEnabled: core.serialization.property(
            "do_not_share_warning_enabled",
            core.serialization.boolean().optionalNullable(),
        ),
        customCodeEnabled: core.serialization.property(
            "custom_code_enabled",
            core.serialization.boolean().optionalNullable(),
        ),
        push: core.serialization.unknown().optionalNullable(),
        totp: core.serialization.unknown().optionalNullable(),
        defaultTemplateSid: core.serialization.property(
            "default_template_sid",
            core.serialization.string().optionalNullable(),
        ),
        whatsapp: core.serialization.unknown().optionalNullable(),
        passkeys: core.serialization.unknown().optionalNullable(),
        verifyEventSubscriptionEnabled: core.serialization.property(
            "verify_event_subscription_enabled",
            core.serialization.boolean().optionalNullable(),
        ),
        dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
        dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
        url: core.serialization.string().optionalNullable(),
        links: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    });

export declare namespace VerifyV2Service {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        friendly_name?: (string | null | undefined) | null;
        code_length?: number | null;
        lookup_enabled?: (boolean | null | undefined) | null;
        psd2_enabled?: (boolean | null | undefined) | null;
        skip_sms_to_landlines?: (boolean | null | undefined) | null;
        dtmf_input_required?: (boolean | null | undefined) | null;
        tts_name?: (string | null | undefined) | null;
        do_not_share_warning_enabled?: (boolean | null | undefined) | null;
        custom_code_enabled?: (boolean | null | undefined) | null;
        push?: (unknown | null | undefined) | null;
        totp?: (unknown | null | undefined) | null;
        default_template_sid?: (string | null | undefined) | null;
        whatsapp?: (unknown | null | undefined) | null;
        passkeys?: (unknown | null | undefined) | null;
        verify_event_subscription_enabled?: (boolean | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
        links?: (Record<string, unknown> | null | undefined) | null;
    }
}
