// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerificationAttemptEnumChannels: core.serialization.Schema<
    serializers.VerificationAttemptEnumChannels.Raw,
    Twilio.VerificationAttemptEnumChannels
> = core.serialization.enum_(["sms", "call", "email", "whatsapp", "rbm"]);

export declare namespace VerificationAttemptEnumChannels {
    export type Raw = "sms" | "call" | "email" | "whatsapp" | "rbm";
}
