// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { VerificationEnumChannel } from "./VerificationEnumChannel.js";

export const VerifyV2ServiceVerification: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceVerification.Raw,
    Twilio.VerifyV2ServiceVerification
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    to: core.serialization.string().optionalNullable(),
    channel: VerificationEnumChannel.optional(),
    status: core.serialization.string().optionalNullable(),
    valid: core.serialization.boolean().optionalNullable(),
    lookup: core.serialization.unknown().optionalNullable(),
    amount: core.serialization.string().optionalNullable(),
    payee: core.serialization.string().optionalNullable(),
    sendCodeAttempts: core.serialization.property(
        "send_code_attempts",
        core.serialization.list(core.serialization.unknown()).optionalNullable(),
    ),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    sna: core.serialization.unknown().optionalNullable(),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyV2ServiceVerification {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        to?: (string | null | undefined) | null;
        channel?: VerificationEnumChannel.Raw | null;
        status?: (string | null | undefined) | null;
        valid?: (boolean | null | undefined) | null;
        lookup?: (unknown | null | undefined) | null;
        amount?: (string | null | undefined) | null;
        payee?: (string | null | undefined) | null;
        send_code_attempts?: (unknown[] | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        sna?: (unknown | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
