// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerificationAttemptEnumMessageStatus: core.serialization.Schema<
    serializers.VerificationAttemptEnumMessageStatus.Raw,
    Twilio.VerificationAttemptEnumMessageStatus
> = core.serialization.enum_([
    "queued",
    "sending",
    "sent",
    "failed",
    "delivered",
    "undelivered",
    "receiving",
    "received",
    "accepted",
    "scheduled",
    "read",
    "partially_delivered",
    "canceled",
]);

export declare namespace VerificationAttemptEnumMessageStatus {
    export type Raw =
        | "queued"
        | "sending"
        | "sent"
        | "failed"
        | "delivered"
        | "undelivered"
        | "receiving"
        | "received"
        | "accepted"
        | "scheduled"
        | "read"
        | "partially_delivered"
        | "canceled";
}
