// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerificationEnumChannel: core.serialization.Schema<
    serializers.VerificationEnumChannel.Raw,
    Twilio.VerificationEnumChannel
> = core.serialization.enum_(["sms", "call", "email", "whatsapp", "sna"]);

export declare namespace VerificationEnumChannel {
    export type Raw = "sms" | "call" | "email" | "whatsapp" | "sna";
}
