// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2Safelist: core.serialization.ObjectSchema<
    serializers.VerifyV2Safelist.Raw,
    Twilio.VerifyV2Safelist
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optionalNullable()),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyV2Safelist {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        phone_number?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
