// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2VerificationAttemptsSummary: core.serialization.ObjectSchema<
    serializers.VerifyV2VerificationAttemptsSummary.Raw,
    Twilio.VerifyV2VerificationAttemptsSummary
> = core.serialization.object({
    totalAttempts: core.serialization.property("total_attempts", core.serialization.number().optional()),
    totalConverted: core.serialization.property("total_converted", core.serialization.number().optional()),
    totalUnconverted: core.serialization.property("total_unconverted", core.serialization.number().optional()),
    conversionRatePercentage: core.serialization.property(
        "conversion_rate_percentage",
        core.serialization.string().optionalNullable(),
    ),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyV2VerificationAttemptsSummary {
    export interface Raw {
        total_attempts?: number | null;
        total_converted?: number | null;
        total_unconverted?: number | null;
        conversion_rate_percentage?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
