// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AccessTokenEnumFactorTypes } from "./AccessTokenEnumFactorTypes.js";

export const VerifyV2ServiceAccessToken: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceAccessToken.Raw,
    Twilio.VerifyV2ServiceAccessToken
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    entityIdentity: core.serialization.property("entity_identity", core.serialization.string().optionalNullable()),
    factorType: core.serialization.property("factor_type", AccessTokenEnumFactorTypes.optional()),
    factorFriendlyName: core.serialization.property(
        "factor_friendly_name",
        core.serialization.string().optionalNullable(),
    ),
    token: core.serialization.string().optionalNullable(),
    url: core.serialization.string().optionalNullable(),
    ttl: core.serialization.number().optional(),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
});

export declare namespace VerifyV2ServiceAccessToken {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        entity_identity?: (string | null | undefined) | null;
        factor_type?: AccessTokenEnumFactorTypes.Raw | null;
        factor_friendly_name?: (string | null | undefined) | null;
        token?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
        ttl?: number | null;
        date_created?: (string | null | undefined) | null;
    }
}
