// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2ServiceMessagingConfiguration: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceMessagingConfiguration.Raw,
    Twilio.VerifyV2ServiceMessagingConfiguration
> = core.serialization.object({
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    country: core.serialization.string().optionalNullable(),
    messagingServiceSid: core.serialization.property(
        "messaging_service_sid",
        core.serialization.string().optionalNullable(),
    ),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyV2ServiceMessagingConfiguration {
    export interface Raw {
        account_sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        country?: (string | null | undefined) | null;
        messaging_service_sid?: (string | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
