// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const VerifyV2ServiceEntityChallengeNotification: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceEntityChallengeNotification.Raw,
    Twilio.VerifyV2ServiceEntityChallengeNotification
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    entitySid: core.serialization.property("entity_sid", core.serialization.string().optionalNullable()),
    identity: core.serialization.string().optionalNullable(),
    challengeSid: core.serialization.property("challenge_sid", core.serialization.string().optionalNullable()),
    priority: core.serialization.string().optionalNullable(),
    ttl: core.serialization.number().optional(),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
});

export declare namespace VerifyV2ServiceEntityChallengeNotification {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        entity_sid?: (string | null | undefined) | null;
        identity?: (string | null | undefined) | null;
        challenge_sid?: (string | null | undefined) | null;
        priority?: (string | null | undefined) | null;
        ttl?: number | null;
        date_created?: (string | null | undefined) | null;
    }
}
