// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { WebhookEnumMethods } from "./WebhookEnumMethods.js";
import { WebhookEnumStatus } from "./WebhookEnumStatus.js";
import { WebhookEnumVersion } from "./WebhookEnumVersion.js";

export const VerifyV2ServiceWebhook: core.serialization.ObjectSchema<
    serializers.VerifyV2ServiceWebhook.Raw,
    Twilio.VerifyV2ServiceWebhook
> = core.serialization.object({
    sid: core.serialization.string().optionalNullable(),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    friendlyName: core.serialization.property("friendly_name", core.serialization.string().optionalNullable()),
    eventTypes: core.serialization.property(
        "event_types",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    status: WebhookEnumStatus.optional(),
    version: WebhookEnumVersion.optional(),
    webhookUrl: core.serialization.property("webhook_url", core.serialization.string().optionalNullable()),
    webhookMethod: core.serialization.property("webhook_method", WebhookEnumMethods.optional()),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    url: core.serialization.string().optionalNullable(),
});

export declare namespace VerifyV2ServiceWebhook {
    export interface Raw {
        sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        friendly_name?: (string | null | undefined) | null;
        event_types?: (string[] | null | undefined) | null;
        status?: WebhookEnumStatus.Raw | null;
        version?: WebhookEnumVersion.Raw | null;
        webhook_url?: (string | null | undefined) | null;
        webhook_method?: WebhookEnumMethods.Raw | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
