// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FormEnumFormTypes } from "./FormEnumFormTypes.js";

export const VerifyV2Form: core.serialization.ObjectSchema<serializers.VerifyV2Form.Raw, Twilio.VerifyV2Form> =
    core.serialization.object({
        formType: core.serialization.property("form_type", FormEnumFormTypes.optional()),
        forms: core.serialization.unknown().optionalNullable(),
        formMeta: core.serialization.property("form_meta", core.serialization.unknown().optionalNullable()),
        url: core.serialization.string().optionalNullable(),
    });

export declare namespace VerifyV2Form {
    export interface Raw {
        form_type?: FormEnumFormTypes.Raw | null;
        forms?: (unknown | null | undefined) | null;
        form_meta?: (unknown | null | undefined) | null;
        url?: (string | null | undefined) | null;
    }
}
