// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookEnumVersion: core.serialization.Schema<
    serializers.WebhookEnumVersion.Raw,
    Twilio.WebhookEnumVersion
> = core.serialization.enum_(["v1", "v2"]);

export declare namespace WebhookEnumVersion {
    export type Raw = "v1" | "v2";
}
