// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookEnumMethods: core.serialization.Schema<
    serializers.WebhookEnumMethods.Raw,
    Twilio.WebhookEnumMethods
> = core.serialization.enum_(["GET", "POST"]);

export declare namespace WebhookEnumMethods {
    export type Raw = "GET" | "POST";
}
