// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WebhookEnumStatus: core.serialization.Schema<serializers.WebhookEnumStatus.Raw, Twilio.WebhookEnumStatus> =
    core.serialization.enum_(["enabled", "disabled"]);

export declare namespace WebhookEnumStatus {
    export type Raw = "enabled" | "disabled";
}
