// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ApprovePasskeyChallengesRequestResponse: core.serialization.ObjectSchema<
    serializers.ApprovePasskeyChallengesRequestResponse.Raw,
    Twilio.ApprovePasskeyChallengesRequestResponse
> = core.serialization.object({
    authenticatorData: core.serialization.string(),
    clientDataJson: core.serialization.property("clientDataJSON", core.serialization.string()),
    signature: core.serialization.string(),
    userHandle: core.serialization.string().optional(),
});

export declare namespace ApprovePasskeyChallengesRequestResponse {
    export interface Raw {
        authenticatorData: string;
        clientDataJSON: string;
        signature: string;
        userHandle?: string | null;
    }
}
