// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ApprovePasskeyChallengesResponseStatus: core.serialization.Schema<
    serializers.ApprovePasskeyChallengesResponseStatus.Raw,
    Twilio.ApprovePasskeyChallengesResponseStatus
> = core.serialization.enum_(["pending", "expired", "approved", "denied"]);

export declare namespace ApprovePasskeyChallengesResponseStatus {
    export type Raw = "pending" | "expired" | "approved" | "denied";
}
