// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ApprovePasskeyChallengesRequestAuthenticatorAttachment: core.serialization.Schema<
    serializers.ApprovePasskeyChallengesRequestAuthenticatorAttachment.Raw,
    Twilio.ApprovePasskeyChallengesRequestAuthenticatorAttachment
> = core.serialization.enum_(["platform", "cross-platform"]);

export declare namespace ApprovePasskeyChallengesRequestAuthenticatorAttachment {
    export type Raw = "platform" | "cross-platform";
}
