// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePasskeyChallengesResponseStatus: core.serialization.Schema<
    serializers.CreatePasskeyChallengesResponseStatus.Raw,
    Twilio.CreatePasskeyChallengesResponseStatus
> = core.serialization.enum_(["pending", "expired", "approved", "denied"]);

export declare namespace CreatePasskeyChallengesResponseStatus {
    export type Raw = "pending" | "expired" | "approved" | "denied";
}
