// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreatePasskeyChallengesResponseFactorType } from "./CreatePasskeyChallengesResponseFactorType.js";
import { CreatePasskeyChallengesResponseRespondedReason } from "./CreatePasskeyChallengesResponseRespondedReason.js";
import { CreatePasskeyChallengesResponseStatus } from "./CreatePasskeyChallengesResponseStatus.js";

export const CreatePasskeyChallengesResponse: core.serialization.ObjectSchema<
    serializers.CreatePasskeyChallengesResponse.Raw,
    Twilio.CreatePasskeyChallengesResponse
> = core.serialization.object({
    options: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    sid: core.serialization.string().optionalNullable(),
    accountSid: core.serialization.property("account_sid", core.serialization.string().optionalNullable()),
    serviceSid: core.serialization.property("service_sid", core.serialization.string().optionalNullable()),
    entitySid: core.serialization.property("entity_sid", core.serialization.string().optionalNullable()),
    identity: core.serialization.string().optionalNullable(),
    factorSid: core.serialization.property("factor_sid", core.serialization.string().optionalNullable()),
    dateCreated: core.serialization.property("date_created", core.serialization.date().optionalNullable()),
    dateUpdated: core.serialization.property("date_updated", core.serialization.date().optionalNullable()),
    dateResponded: core.serialization.property("date_responded", core.serialization.date().optionalNullable()),
    expirationDate: core.serialization.property("expiration_date", core.serialization.date().optionalNullable()),
    status: CreatePasskeyChallengesResponseStatus.optional(),
    respondedReason: core.serialization.property(
        "responded_reason",
        CreatePasskeyChallengesResponseRespondedReason.optional(),
    ),
    details: core.serialization.unknown().optionalNullable(),
    hiddenDetails: core.serialization.property("hidden_details", core.serialization.unknown().optionalNullable()),
    metadata: core.serialization.unknown().optionalNullable(),
    factorType: core.serialization.property("factor_type", CreatePasskeyChallengesResponseFactorType.optional()),
    url: core.serialization.string().optionalNullable(),
    links: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
});

export declare namespace CreatePasskeyChallengesResponse {
    export interface Raw {
        options?: Record<string, unknown> | null;
        sid?: (string | null | undefined) | null;
        account_sid?: (string | null | undefined) | null;
        service_sid?: (string | null | undefined) | null;
        entity_sid?: (string | null | undefined) | null;
        identity?: (string | null | undefined) | null;
        factor_sid?: (string | null | undefined) | null;
        date_created?: (string | null | undefined) | null;
        date_updated?: (string | null | undefined) | null;
        date_responded?: (string | null | undefined) | null;
        expiration_date?: (string | null | undefined) | null;
        status?: CreatePasskeyChallengesResponseStatus.Raw | null;
        responded_reason?: CreatePasskeyChallengesResponseRespondedReason.Raw | null;
        details?: (unknown | null | undefined) | null;
        hidden_details?: (unknown | null | undefined) | null;
        metadata?: (unknown | null | undefined) | null;
        factor_type?: CreatePasskeyChallengesResponseFactorType.Raw | null;
        url?: (string | null | undefined) | null;
        links?: (Record<string, unknown> | null | undefined) | null;
    }
}
