// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePasskeyChallengesResponseRespondedReason: core.serialization.Schema<
    serializers.CreatePasskeyChallengesResponseRespondedReason.Raw,
    Twilio.CreatePasskeyChallengesResponseRespondedReason
> = core.serialization.enum_(["none", "not_needed", "not_requested"]);

export declare namespace CreatePasskeyChallengesResponseRespondedReason {
    export type Raw = "none" | "not_needed" | "not_requested";
}
