// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListChallengesResponseMeta: core.serialization.ObjectSchema<
    serializers.ListChallengesResponseMeta.Raw,
    Twilio.ListChallengesResponseMeta
> = core.serialization.object({
    firstPageUrl: core.serialization.property("first_page_url", core.serialization.string().optional()),
    key: core.serialization.string().optional(),
    nextPageUrl: core.serialization.property("next_page_url", core.serialization.string().optionalNullable()),
    page: core.serialization.number().optional(),
    pageSize: core.serialization.property("page_size", core.serialization.number().optional()),
    previousPageUrl: core.serialization.property("previous_page_url", core.serialization.string().optionalNullable()),
    url: core.serialization.string().optional(),
});

export declare namespace ListChallengesResponseMeta {
    export interface Raw {
        first_page_url?: string | null;
        key?: string | null;
        next_page_url?: (string | null | undefined) | null;
        page?: number | null;
        page_size?: number | null;
        previous_page_url?: (string | null | undefined) | null;
        url?: string | null;
    }
}
