// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateNotificationsRequest: core.serialization.Schema<
    serializers.CreateNotificationsRequest.Raw,
    Omit<Twilio.CreateNotificationsRequest, "serviceSid" | "identity" | "challengeSid">
> = core.serialization.object({
    ttl: core.serialization.property("Ttl", core.serialization.number().optional()),
});

export declare namespace CreateNotificationsRequest {
    export interface Raw {
        Ttl?: number | null;
    }
}
