// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         code: "1234",
 *         to: "+15017122661",
 *         verificationSid: "VEaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 *         amount: "\u20AC39.99",
 *         payee: "Acme Inc."
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         code: "123456",
 *         to: "recipient@foo.com",
 *         verificationSid: "VEaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "+15017122661"
 *     }
 */
export interface CreateVerificationChecksRequest {
    /** The SID of the verification [Service](https://www.twilio.com/docs/verify/api/service) to create the resource under. */
    serviceSid: string;
    /** The 4-10 character string being verified. */
    code?: string;
    /** The phone number or [email](https://www.twilio.com/docs/verify/email) to verify. Either this parameter or the `verification_sid` must be specified. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164). */
    to?: string;
    /** A SID that uniquely identifies the Verification Check. Either this parameter or the `to` phone number/[email](https://www.twilio.com/docs/verify/email) must be specified. */
    verificationSid?: string;
    /** The amount of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled. */
    amount?: string;
    /** The payee of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled. */
    payee?: string;
    /** A sna client token received in sna url invocation response needs to be passed in Verification Check request and should match to get successful response. */
    snaClientToken?: string;
}
