// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListTemplatesResponse {
    templates?: Twilio.VerifyV2VerificationTemplate[];
    meta?: Twilio.ListTemplatesResponseMeta;
}
