// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListMessagingConfigurationsResponse {
    messagingConfigurations?: Twilio.VerifyV2ServiceMessagingConfiguration[];
    meta?: Twilio.ListMessagingConfigurationsResponseMeta;
}
