// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { NewFactorEnumFactorTypes } from "../../../../types/NewFactorEnumFactorTypes.js";
import { NewFactorEnumNotificationPlatforms } from "../../../../types/NewFactorEnumNotificationPlatforms.js";
import { NewFactorEnumTotpAlgorithms } from "../../../../types/NewFactorEnumTotpAlgorithms.js";

export const CreateFactorsRequest: core.serialization.Schema<
    serializers.CreateFactorsRequest.Raw,
    Omit<Twilio.CreateFactorsRequest, "serviceSid" | "identity">
> = core.serialization.object({
    friendlyName: core.serialization.property("FriendlyName", core.serialization.string()),
    factorType: core.serialization.property("FactorType", NewFactorEnumFactorTypes),
    bindingAlg: core.serialization.property("Binding.Alg", core.serialization.string().optional()),
    bindingPublicKey: core.serialization.property("Binding.PublicKey", core.serialization.string().optional()),
    configAppId: core.serialization.property("Config.AppId", core.serialization.string().optional()),
    configNotificationPlatform: core.serialization.property(
        "Config.NotificationPlatform",
        NewFactorEnumNotificationPlatforms.optional(),
    ),
    configNotificationToken: core.serialization.property(
        "Config.NotificationToken",
        core.serialization.string().optional(),
    ),
    configSdkVersion: core.serialization.property("Config.SdkVersion", core.serialization.string().optional()),
    bindingSecret: core.serialization.property("Binding.Secret", core.serialization.string().optional()),
    configTimeStep: core.serialization.property("Config.TimeStep", core.serialization.number().optional()),
    configSkew: core.serialization.property("Config.Skew", core.serialization.number().optional()),
    configCodeLength: core.serialization.property("Config.CodeLength", core.serialization.number().optional()),
    configAlg: core.serialization.property("Config.Alg", NewFactorEnumTotpAlgorithms.optional()),
    metadata: core.serialization.property("Metadata", core.serialization.unknown().optional()),
});

export declare namespace CreateFactorsRequest {
    export interface Raw {
        FriendlyName: string;
        FactorType: NewFactorEnumFactorTypes.Raw;
        "Binding.Alg"?: string | null;
        "Binding.PublicKey"?: string | null;
        "Config.AppId"?: string | null;
        "Config.NotificationPlatform"?: NewFactorEnumNotificationPlatforms.Raw | null;
        "Config.NotificationToken"?: string | null;
        "Config.SdkVersion"?: string | null;
        "Binding.Secret"?: string | null;
        "Config.TimeStep"?: number | null;
        "Config.Skew"?: number | null;
        "Config.CodeLength"?: number | null;
        "Config.Alg"?: NewFactorEnumTotpAlgorithms.Raw | null;
        Metadata?: unknown | null;
    }
}
