// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { CreatePasskeyFactorsRequestConfig } from "../../types/CreatePasskeyFactorsRequestConfig.js";

export const CreatePasskeyFactorsRequest: core.serialization.Schema<
    serializers.CreatePasskeyFactorsRequest.Raw,
    Omit<Twilio.CreatePasskeyFactorsRequest, "serviceSid">
> = core.serialization.object({
    friendlyName: core.serialization.property("friendly_name", core.serialization.string()),
    identity: core.serialization.string(),
    config: CreatePasskeyFactorsRequestConfig.optional(),
});

export declare namespace CreatePasskeyFactorsRequest {
    export interface Raw {
        friendly_name: string;
        identity: string;
        config?: CreatePasskeyFactorsRequestConfig.Raw | null;
    }
}
