// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { FactorEnumTotpAlgorithms } from "../../../../types/FactorEnumTotpAlgorithms.js";

export const UpdateFactorsRequest: core.serialization.Schema<
    serializers.UpdateFactorsRequest.Raw,
    Omit<Twilio.UpdateFactorsRequest, "serviceSid" | "identity" | "sid">
> = core.serialization.object({
    authPayload: core.serialization.property("AuthPayload", core.serialization.string().optional()),
    friendlyName: core.serialization.property("FriendlyName", core.serialization.string().optional()),
    configNotificationToken: core.serialization.property(
        "Config.NotificationToken",
        core.serialization.string().optional(),
    ),
    configSdkVersion: core.serialization.property("Config.SdkVersion", core.serialization.string().optional()),
    configTimeStep: core.serialization.property("Config.TimeStep", core.serialization.number().optional()),
    configSkew: core.serialization.property("Config.Skew", core.serialization.number().optional()),
    configCodeLength: core.serialization.property("Config.CodeLength", core.serialization.number().optional()),
    configAlg: core.serialization.property("Config.Alg", FactorEnumTotpAlgorithms.optional()),
    configNotificationPlatform: core.serialization.property(
        "Config.NotificationPlatform",
        core.serialization.string().optional(),
    ),
});

export declare namespace UpdateFactorsRequest {
    export interface Raw {
        AuthPayload?: string | null;
        FriendlyName?: string | null;
        "Config.NotificationToken"?: string | null;
        "Config.SdkVersion"?: string | null;
        "Config.TimeStep"?: number | null;
        "Config.Skew"?: number | null;
        "Config.CodeLength"?: number | null;
        "Config.Alg"?: FactorEnumTotpAlgorithms.Raw | null;
        "Config.NotificationPlatform"?: string | null;
    }
}
