// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { VerifyPasskeyFactorsRequestAuthenticatorAttachment } from "../../types/VerifyPasskeyFactorsRequestAuthenticatorAttachment.js";
import { VerifyPasskeyFactorsRequestResponse } from "../../types/VerifyPasskeyFactorsRequestResponse.js";
import { VerifyPasskeyFactorsRequestType } from "../../types/VerifyPasskeyFactorsRequestType.js";

export const VerifyPasskeyFactorsRequest: core.serialization.Schema<
    serializers.VerifyPasskeyFactorsRequest.Raw,
    Omit<Twilio.VerifyPasskeyFactorsRequest, "serviceSid">
> = core.serialization.object({
    id: core.serialization.string().optional(),
    rawId: core.serialization.string().optional(),
    authenticatorAttachment: VerifyPasskeyFactorsRequestAuthenticatorAttachment.optional(),
    type: VerifyPasskeyFactorsRequestType.optional(),
    response: VerifyPasskeyFactorsRequestResponse,
});

export declare namespace VerifyPasskeyFactorsRequest {
    export interface Raw {
        id?: string | null;
        rawId?: string | null;
        authenticatorAttachment?: VerifyPasskeyFactorsRequestAuthenticatorAttachment.Raw | null;
        type?: VerifyPasskeyFactorsRequestType.Raw | null;
        response: VerifyPasskeyFactorsRequestResponse.Raw;
    }
}
