// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2Service } from "../../../types/VerifyV2Service.js";
import { ListServicesResponseMeta } from "./ListServicesResponseMeta.js";

export const ListServicesResponse: core.serialization.ObjectSchema<
    serializers.ListServicesResponse.Raw,
    Twilio.ListServicesResponse
> = core.serialization.object({
    services: core.serialization.list(VerifyV2Service).optional(),
    meta: ListServicesResponseMeta.optional(),
});

export declare namespace ListServicesResponse {
    export interface Raw {
        services?: VerifyV2Service.Raw[] | null;
        meta?: ListServicesResponseMeta.Raw | null;
    }
}
