// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListBucketsResponse {
    buckets?: Twilio.VerifyV2ServiceRateLimitBucket[];
    meta?: Twilio.ListBucketsResponseMeta;
}
