// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sid: "Sid"
 *     }
 */
export interface DeleteServicesRequest {
    /** The Twilio-provided string that uniquely identifies the Verification Service resource to delete. */
    sid: string;
}
