// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListServicesRequest {
    /** How many resources to return in each list page. The default is 50, and the maximum is 1000. */
    pageSize?: number;
    /** The page index. This value is simply for client state. */
    page?: number;
    /** The page token. This is provided by the API. */
    pageToken?: string;
}
