// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sid: "Sid",
 *         friendlyName: "name",
 *         codeLength: 4,
 *         lookupEnabled: false,
 *         skipSmsToLandlines: false,
 *         dtmfInputRequired: false,
 *         ttsName: "name",
 *         psd2Enabled: false,
 *         doNotShareWarningEnabled: false,
 *         customCodeEnabled: true,
 *         pushIncludeDate: false,
 *         pushFcmCredentialSid: "CRbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
 *         totpIssuer: "test-issuer",
 *         totpTimeStep: 30,
 *         totpCodeLength: 3,
 *         totpSkew: 2,
 *         defaultTemplateSid: "HJaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 *         verifyEventSubscriptionEnabled: false
 *     }
 */
export interface UpdateServicesRequest {
    /** The Twilio-provided string that uniquely identifies the Service resource to update. */
    sid: string;
    /** A descriptive string that you create to describe the verification service. It can be up to 32 characters long. **This value should not contain PII.** */
    friendlyName?: string;
    /** The length of the verification code to generate. Must be an integer value between 4 and 10, inclusive. */
    codeLength?: number;
    /** Whether to perform a lookup with each verification started and return info about the phone number. */
    lookupEnabled?: boolean;
    /** Whether to skip sending SMS verifications to landlines. Requires `lookup_enabled`. */
    skipSmsToLandlines?: boolean;
    /** Whether to ask the user to press a number before delivering the verify code in a phone call. */
    dtmfInputRequired?: boolean;
    /** The name of an alternative text-to-speech service to use in phone calls. Applies only to TTS languages. */
    ttsName?: string;
    /** Whether to pass PSD2 transaction parameters when starting a verification. */
    psd2Enabled?: boolean;
    /** Whether to add a privacy warning at the end of an SMS. **Disabled by default and applies only for SMS.** */
    doNotShareWarningEnabled?: boolean;
    /** Whether to allow sending verifications with a custom code instead of a randomly generated one. */
    customCodeEnabled?: boolean;
    /** Optional configuration for the Push factors. If true, include the date in the Challenge's response. Otherwise, the date is omitted from the response. See [Challenge](https://www.twilio.com/docs/verify/api/challenge) resource’s details parameter for more info. Default: false. **Deprecated** do not use this parameter. */
    pushIncludeDate?: boolean;
    /** Optional configuration for the Push factors. Set the APN Credential for this service. This will allow to send push notifications to iOS devices. See [Credential Resource](https://www.twilio.com/docs/notify/api/credential-resource) */
    pushApnCredentialSid?: string;
    /** Optional configuration for the Push factors. Set the FCM Credential for this service. This will allow to send push notifications to Android devices. See [Credential Resource](https://www.twilio.com/docs/notify/api/credential-resource) */
    pushFcmCredentialSid?: string;
    /** Optional configuration for the TOTP factors. Set TOTP Issuer for this service. This will allow to configure the issuer of the TOTP URI. */
    totpIssuer?: string;
    /** Optional configuration for the TOTP factors. Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated every time_step seconds. Must be between 20 and 60 seconds, inclusive. Defaults to 30 seconds */
    totpTimeStep?: number;
    /** Optional configuration for the TOTP factors. Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive. Defaults to 6 */
    totpCodeLength?: number;
    /** Optional configuration for the TOTP factors. The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be between 0 and 2, inclusive. Defaults to 1 */
    totpSkew?: number;
    /** The default message [template](https://www.twilio.com/docs/verify/api/templates). Will be used for all SMS verifications unless explicitly overriden. SMS channel only. */
    defaultTemplateSid?: string;
    /** The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services) to associate with the Verification Service. */
    whatsappMsgServiceSid?: string;
    /** The WhatsApp number to use as the sender of the verification messages. This number must be associated with the WhatsApp Message Service. */
    whatsappFrom?: string;
    /** The Relying Party ID for Passkeys. This is the domain of your application, e.g. `example.com`. It is used to identify your application when creating Passkeys. */
    passkeysRelyingPartyId?: string;
    /** The Relying Party Name for Passkeys. This is the name of your application, e.g. `Example App`. It is used to identify your application when creating Passkeys. */
    passkeysRelyingPartyName?: string;
    /** The Relying Party Origins for Passkeys. This is the origin of your application, e.g. `login.example.com,www.example.com`. It is used to identify your application when creating Passkeys, it can have multiple origins split by `,`. */
    passkeysRelyingPartyOrigins?: string;
    /** The Authenticator Attachment for Passkeys. This is the type of authenticator that will be used to create Passkeys. It can be empty or it can have the values `platform`, `cross-platform` or `any`. */
    passkeysAuthenticatorAttachment?: string;
    /** Indicates whether credentials must be discoverable by the authenticator. It can be empty or it can have the values `required`, `preferred` or `discouraged`. */
    passkeysDiscoverableCredentials?: string;
    /** The User Verification for Passkeys. This is the type of user verification that will be used to create Passkeys. It can be empty or it can have the values `required`, `preferred` or `discouraged`. */
    passkeysUserVerification?: string;
    /** Whether to allow verifications from the service to reach the stream-events sinks if configured */
    verifyEventSubscriptionEnabled?: boolean;
}
