// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "+15017122661",
 *         channel: "sms",
 *         customFriendlyName: "custom_friendly_name",
 *         sendDigits: "ww1",
 *         locale: "en",
 *         customCode: "custom_code",
 *         amount: "\u20AC39.99",
 *         payee: "Acme Inc.",
 *         appHash: "AAAAAAAAAAA",
 *         templateSid: "HJaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 *         templateCustomSubstitutions: "{\"AppName\": \"MyApp\", \"Contact\":\"12345689\"}",
 *         riskCheck: "enable",
 *         tags: "{\"tenant_id\": \"12345\"}"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "+15017122661",
 *         channel: "whatsapp",
 *         customFriendlyName: "custom_friendly_name",
 *         locale: "en",
 *         customCode: "custom_code"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "mail@email.com",
 *         channel: "email",
 *         locale: "en",
 *         customCode: "custom_code",
 *         amount: "\u20AC39.99",
 *         payee: "Acme Inc.",
 *         channelConfiguration: "{\"from\": \"foo@bar.com\", \"from_name\": \"Bar Inc.\", \"substitutions\": { \"username\": \"ms. baz\" }, \"template_id\": \"Dxxxxxxxxxx\"}"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "+15017122661",
 *         channel: "sms",
 *         sendDigits: "ww1",
 *         locale: "en",
 *         customCode: "custom_code",
 *         rateLimits: "{\"my_rate_limit_key\": \"abc\"}"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "+15017122661",
 *         channel: "sna"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "+15017122661",
 *         channel: "auto",
 *         deviceIp: "0.000.00.000"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         to: "+15017122661",
 *         channel: "sms"
 *     }
 */
export interface CreateVerificationsRequest {
    /** The SID of the verification [Service](https://www.twilio.com/docs/verify/api/service) to create the resource under. */
    serviceSid: string;
    /** The phone number or [email](https://www.twilio.com/docs/verify/email) to verify. Phone numbers must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164). */
    to: string;
    /** The verification method to use. One of: [`email`](https://www.twilio.com/docs/verify/email), `sms`, `whatsapp`, `call`, `sna` or `auto`. */
    channel: string;
    /** A custom user defined friendly name that overwrites the existing one in the verification message */
    customFriendlyName?: string;
    /** The text of a custom message to use for the verification [DEPRECATED]. */
    customMessage?: string;
    /** The digits to send after a phone call is answered, for example, to dial an extension. For more information, see the Programmable Voice documentation of [sendDigits](https://www.twilio.com/docs/voice/twiml/number#attributes-sendDigits). */
    sendDigits?: string;
    /** Locale will automatically resolve based on phone number country code for SMS, WhatsApp, and call channel verifications. It will fallback to English or the template’s default translation if the selected translation is not available. This parameter will override the automatic locale resolution. [See supported languages and more information here](https://www.twilio.com/docs/verify/supported-languages). */
    locale?: string;
    /** A pre-generated code to use for verification. The code can be between 4 and 10 characters, inclusive. */
    customCode?: string;
    /** The amount of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled. */
    amount?: string;
    /** The payee of the associated PSD2 compliant transaction. Requires the PSD2 Service flag enabled. */
    payee?: string;
    /** The custom key-value pairs of Programmable Rate Limits. Keys correspond to `unique_name` fields defined when [creating your Rate Limit](https://www.twilio.com/docs/verify/api/service-rate-limits). Associated value pairs represent values in the request that you are rate limiting on. You may include multiple Rate Limit values in each request. */
    rateLimits?: unknown;
    /** [`email`](https://www.twilio.com/docs/verify/email) channel configuration in json format. The fields 'from' and 'from_name' are optional but if included the 'from' field must have a valid email address. */
    channelConfiguration?: unknown;
    /** Your [App Hash](https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string) to be appended at the end of your verification SMS body. Applies only to SMS. Example SMS body: `<#> Your AppName verification code is: 1234 He42w354ol9`. */
    appHash?: string;
    /** The message [template](https://www.twilio.com/docs/verify/api/templates). If provided, will override the default template for the Service. SMS and Voice channels only. */
    templateSid?: string;
    /** A stringified JSON object in which the keys are the template's special variables and the values are the variables substitutions. */
    templateCustomSubstitutions?: string;
    /** Strongly encouraged if using the auto channel. The IP address of the client's device. If provided, it has to be a valid IPv4 or IPv6 address. */
    deviceIp?: string;
    /** An optional Boolean value to indicate the requirement of sna client token in the SNA URL invocation response for added security. This token must match in the Verification Check request to confirm phone number verification. */
    enableSnaClientToken?: boolean;
    riskCheck?: Twilio.VerificationEnumRiskCheck;
    /** A string containing a JSON map of key value pairs of tags to be recorded as metadata for the message. The object may contain up to 10 tags. Keys and values can each be up to 128 characters in length. */
    tags?: string;
}
