// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         sid: "Sid"
 *     }
 */
export interface FetchVerificationsRequest {
    /** The SID of the verification [Service](https://www.twilio.com/docs/verify/api/service) to fetch the resource from. */
    serviceSid: string;
    /** The Twilio-provided string that uniquely identifies the Verification resource to fetch. */
    sid: string;
}
