// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         sid: "Sid",
 *         status: "canceled"
 *     }
 *
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         sid: "Sid",
 *         status: "approved"
 *     }
 */
export interface UpdateVerificationsRequest {
    /** The SID of the verification [Service](https://www.twilio.com/docs/verify/api/service) to update the resource from. */
    serviceSid: string;
    /** The Twilio-provided string that uniquely identifies the Verification resource to update. */
    sid: string;
    status: Twilio.VerificationEnumStatus;
}
