// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { VerifyV2VerificationAttempt } from "../../../types/VerifyV2VerificationAttempt.js";
import { ListVerificationAttemptsResponseMeta } from "./ListVerificationAttemptsResponseMeta.js";

export const ListVerificationAttemptsResponse: core.serialization.ObjectSchema<
    serializers.ListVerificationAttemptsResponse.Raw,
    Twilio.ListVerificationAttemptsResponse
> = core.serialization.object({
    attempts: core.serialization.list(VerifyV2VerificationAttempt).optional(),
    meta: ListVerificationAttemptsResponseMeta.optional(),
});

export declare namespace ListVerificationAttemptsResponse {
    export interface Raw {
        attempts?: VerifyV2VerificationAttempt.Raw[] | null;
        meta?: ListVerificationAttemptsResponseMeta.Raw | null;
    }
}
