// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListServicesResponse {
    services?: Twilio.VerifyV2Service[];
    meta?: Twilio.ListServicesResponseMeta;
}
