// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../index.js";

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         friendlyName: "name",
 *         eventTypes: ["factor.deleted", "factor.verified"],
 *         webhookUrl: "https://owlbank.twilio.com",
 *         version: "v2"
 *     }
 */
export interface CreateWebhooksRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** The string that you assigned to describe the webhook. **This value should not contain PII.** */
    friendlyName: string;
    /** The array of events that this Webhook is subscribed to. Possible event types: `*, factor.deleted, factor.created, factor.verified, challenge.approved, challenge.denied` */
    eventTypes: string[];
    /** The URL associated with this Webhook. */
    webhookUrl: string;
    status?: Twilio.WebhookEnumStatus;
    version?: Twilio.WebhookEnumVersion;
}
