// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         serviceSid: "ServiceSid",
 *         sid: "Sid"
 *     }
 */
export interface DeleteWebhooksRequest {
    /** The unique SID identifier of the Service. */
    serviceSid: string;
    /** The Twilio-provided string that uniquely identifies the Webhook resource to delete. */
    sid: string;
}
