// This file was auto-generated by Fern from our API Definition.

export const CreatePasskeyFactorsRequestConfigDiscoverableCredentials = {
    Required: "required",
    Preferred: "preferred",
    Discouraged: "discouraged",
} as const;
export type CreatePasskeyFactorsRequestConfigDiscoverableCredentials =
    (typeof CreatePasskeyFactorsRequestConfigDiscoverableCredentials)[keyof typeof CreatePasskeyFactorsRequestConfigDiscoverableCredentials];
