// This file was auto-generated by Fern from our API Definition.

/**
 * Contains the information of the party requesting the user for authentication
 */
export interface CreatePasskeyFactorsRequestConfigRelyingParty {
    id?: string;
    name?: string;
    origins?: string[];
}
