// This file was auto-generated by Fern from our API Definition.

export const CreatePasskeyFactorsRequestConfigAuthenticatorAttachment = {
    Platform: "platform",
    CrossPlatform: "cross-platform",
    Any: "any",
} as const;
export type CreatePasskeyFactorsRequestConfigAuthenticatorAttachment =
    (typeof CreatePasskeyFactorsRequestConfigAuthenticatorAttachment)[keyof typeof CreatePasskeyFactorsRequestConfigAuthenticatorAttachment];
