// This file was auto-generated by Fern from our API Definition.

export const CreatePasskeyFactorsRequestConfigUserVerification = {
    Required: "required",
    Preferred: "preferred",
    Discouraged: "discouraged",
} as const;
export type CreatePasskeyFactorsRequestConfigUserVerification =
    (typeof CreatePasskeyFactorsRequestConfigUserVerification)[keyof typeof CreatePasskeyFactorsRequestConfigUserVerification];
