// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface CreatePasskeyFactorsRequestConfig {
    /** Contains the information of the party requesting the user for authentication */
    relyingParty?: Twilio.CreatePasskeyFactorsRequestConfigRelyingParty;
    authenticatorAttachment?: Twilio.CreatePasskeyFactorsRequestConfigAuthenticatorAttachment;
    discoverableCredentials?: Twilio.CreatePasskeyFactorsRequestConfigDiscoverableCredentials;
    userVerification?: Twilio.CreatePasskeyFactorsRequestConfigUserVerification;
}
