// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface ListFactorsResponse {
    factors?: Twilio.VerifyV2ServiceEntityFactor[];
    meta?: Twilio.ListFactorsResponseMeta;
}
