// This file was auto-generated by Fern from our API Definition.

/** The Status of this Factor. One of `unverified` or `verified`. */
export const VerifyPasskeyFactorsResponseStatus = {
    Unverified: "unverified",
    Verified: "verified",
} as const;
export type VerifyPasskeyFactorsResponseStatus =
    (typeof VerifyPasskeyFactorsResponseStatus)[keyof typeof VerifyPasskeyFactorsResponseStatus];
