// This file was auto-generated by Fern from our API Definition.

export const VerifyPasskeyFactorsRequestResponseTransportsItem = {
    Usb: "usb",
    Nfc: "nfc",
    Ble: "ble",
    SmartCard: "smart-card",
    Internal: "internal",
    Hybrid: "hybrid",
} as const;
export type VerifyPasskeyFactorsRequestResponseTransportsItem =
    (typeof VerifyPasskeyFactorsRequestResponseTransportsItem)[keyof typeof VerifyPasskeyFactorsRequestResponseTransportsItem];
