// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../index.js";

export interface VerifyPasskeyFactorsResponse {
    /** A 34 character string that uniquely identifies this Factor. */
    sid?: string | null;
    /** The unique SID identifier of the Account. */
    accountSid?: string | null;
    /** The unique SID identifier of the Service. */
    serviceSid?: string | null;
    /** The unique SID identifier of the Entity. */
    entitySid?: string | null;
    /** Customer unique identity for the Entity owner of the Factor. */
    identity?: string | null;
    /** The date that this Factor was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateCreated?: Date | null;
    /** The date that this Factor was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. */
    dateUpdated?: Date | null;
    /** A human readable description of this resource, up to 64 characters. */
    friendlyName?: string | null;
    /** The Status of this Factor. One of `unverified` or `verified`. */
    status?: Twilio.VerifyPasskeyFactorsResponseStatus;
    /** The Type of this Factor. Currently `push` and `totp` are supported. */
    factorType?: Twilio.VerifyPasskeyFactorsResponseFactorType;
    /** An object that contains configurations specific to a `factor_type`. */
    config?: unknown | null;
    /** Custom metadata associated with the factor. */
    metadata?: unknown | null;
    /** The URL of this resource. */
    url?: string | null;
}
