// This file was auto-generated by Fern from our API Definition.

import type * as Twilio from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AccessTokenEnumFactorTypes } from "../../../../types/AccessTokenEnumFactorTypes.js";

export const CreateAccessTokensRequest: core.serialization.Schema<
    serializers.CreateAccessTokensRequest.Raw,
    Omit<Twilio.CreateAccessTokensRequest, "serviceSid">
> = core.serialization.object({
    identity: core.serialization.property("Identity", core.serialization.string()),
    factorType: core.serialization.property("FactorType", AccessTokenEnumFactorTypes),
    factorFriendlyName: core.serialization.property("FactorFriendlyName", core.serialization.string().optional()),
    ttl: core.serialization.property("Ttl", core.serialization.number().optional()),
});

export declare namespace CreateAccessTokensRequest {
    export interface Raw {
        Identity: string;
        FactorType: AccessTokenEnumFactorTypes.Raw;
        FactorFriendlyName?: string | null;
        Ttl?: number | null;
    }
}
